### PR TITLE
Fix facedown permanent with adventure

### LINKED ISSUE #4346: Adventure cards put onto the battlefield face down retain their face-up characteristics
**Describe the bug**
When a card with an Adventure is put onto the battlefield face down by an effect such as that of Yedora, Grave Gardener or The Cyber-Controller, it retains all of its face-up characteristics rather than gaining the characteristics created by the effect (e.g. if Yedora returns a Curious Pair to the battlefield, it will still be a 1/3 green Human Peasant creature named Curious Pair rather than a colorless Forest land).

**To Reproduce**
1. Place a creature with an Adventure onto the battlefield alongside Yedora, Grave Gardener
2. Kill the Adventure creature
3. Yedora's triggered ability causes the creature to return to the battlefield, but not as a Forest

**Expected behavior**
Adventure cards placed onto the battlefield face down should have the same characteristics as the effect dictates for any other card; in the given example, the creature should be a Forest land with no name, no color, no abilities beyond the intrinsic Forest "{T}: Add {G}", and so on.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.6.60-SNAPSHOT-12-09

**Additional context**
They are still face down and can be turned face up with Ixidor, Reality Sculptor and similar effects, though this does not trigger abilities such as that of Secret Plans. Manifesting notably works as expected, as does turning an already face-up creature face down with Ixidron or Illithid Harvester; this issue seems to apply only to ChangeZone with FaceDown$ True.

### LINKED ISSUE #4374: java.lang.IndexOutOfBoundsException Error with Cybership
**Describe the bug**
The A.I. attacked another A.I. with Cybership, the trigger went on the stack and they put the top two cards onto their field as Cybermen, then the game froze. I looked at the log and this is the last thing on it, so I assume it pertains to the issue at hand.

`Correcting zone for Face-down card (H1)
Correcting zone for Face-down card (H2)
Game-2 > java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:361)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at forge.game.trigger.TriggerChangesZone.performTest(TriggerChangesZone.java:115)
	at forge.game.trigger.TriggerHandler.canRunTrigger(TriggerHandler.java:436)
	at forge.game.trigger.TriggerHandler.getActiveTrigger(TriggerHandler.java:617)
	at forge.game.trigger.TriggerHandler.collectTriggerForWaiting(TriggerHandler.java:188)
	at forge.game.trigger.TriggerHandler.resetActiveTriggers(TriggerHandler.java:212)
	at forge.game.trigger.TriggerHandler.resetActiveTriggers(TriggerHandler.java:208)
	at forge.game.zone.MagicStack.removeCardFromStack(MagicStack.java:607)
	at forge.game.zone.MagicStack.finishResolving(MagicStack.java:583)
	at forge.game.zone.MagicStack.resolveStack(MagicStack.java:568)
	at forge.game.phase.PhaseHandler.startFirstTurn(PhaseHandler.java:1131)
	at forge.game.GameAction.startGame(GameAction.java:2114)
	at forge.game.Match.startGame(Match.java:90)
	at forge.gamemodes.match.HostedMatch$2.run(HostedMatch.java:255)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)`

**Screenshots**
I don't know if it helps, but here's a screen of the game when it happened.

Screenshot_20231213_211915 cleaned cleaned

**Desktop (please complete the following information):**
 - OS: Kubuntu 22.04
 - Browser [e.g. chrome, safari] <- Always wondered, but why does this even matter?
 - Version [e.g. 22] <- I assume you're asking for the Forge version? forge-gui-desktop-1.6.60-SNAPSHOT-12-12

### LINKED ISSUE #4380: Card/Rules Bug: Timothar Barron of Bats and a Stolen Creature
**Describe the bug**
When Timothar Barron of Bats exiles a stolen creature that has been turned into a vampire, Eg: Stealing an opponents creature with captivating vampire, when the bat deals combat damage and returns the creature it returns the creature under its owners control.

**To Reproduce**
1. Steal an opponents creature while controlling Timothar and something that turns it into a vampire
2. Kill the creature and pay for Timothar's ability
3. Connect with the bat that has the triggered ability to return the stolen creature

**Expected behavior**
The token should return the creature to the control of whomever controlled the token when the combat damage was dealt as per the Oracle rulings for Timothar
Ruling: The controller of the Bat token as it deals combat damage to a player will be the controller of its triggered ability, and the exiled card will be returned to the battlefield under that player's control.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version: 1.6.60

### PR DESCRIPTION
**Pull request by tool4ever**
Closes #4346
Closes #4374
Closes #4380

### CODE REVIEW

**Review by Hanmac — APPROVED** [review]

File: forge-ai/src/main/java/forge/ai/ability/FogAi.java [hunk 1]
```diff
@@ -130,7 +130,7 @@ private int countAvailableFogs(Player ai) {
 
         for (Card c : ai.getCardsIn(ZoneType.Hand)) {
             for (SpellAbility ability : c.getSpellAbilities()) {
-                if (ability.getApi().equals(ApiType.Fog)) {
+                if (ability.getApi() != null && ability.getApi().equals(ApiType.Fog)) {
```
Comment (Hanmac) [inline forge-ai/src/main/java/forge/ai/ability/FogAi.java:133]: you could flip it `ApiType.Fog.equals(ability.getApi())`

otherwise we might look for why the API is null

Comment (tool4ever) [reply forge-ai/src/main/java/forge/ai/ability/FogAi.java]: It can happen with something like Forestell special ability

So I don't think it's a bug

**Review by Hanmac — APPROVED** [review]
