### PR TITLE
Refresh active triggers after statics from ETB

### LINKED ISSUE #5557: Behavior on Evolve mechanic on Propagator Drone incomplete
**Describe the bug**
When Propagator Drone enters the battlefield with existing creature tokens in play, the tokens do not get +1/+1 counters from Evolve. Propagator Drone specifically mentions in it's reminder text that they should see this creature enter and would trigger. Later creature ETBs trigger Evolve correctly, just not the original for Drone itself entering.

**To Reproduce**
1. Build a board state with Eldrazi Spawn or Scion creature tokens in play
2. Cast Propagator Drone and have it successfully enter the battlefield
3. No counters will be added to Spawns or Scions in play
4. Reference reminder text on Propagator under its ability. Specifically, 'Creature tokens you control have evolve. (They have "Whenever a creature enters the battlefield under your control, if it has greater power or toughness than this token, put a +1/+1 counter on this token." **_They see this creature enter_**.)'

**Expected behavior**
Existing creature tokens you control with less than 2 power or toughness should receive a +1/+1 counter on them when Propagator Drone enters.

**Screenshots**
Untitled

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 64-bit
 - Version: 1.6.63
In the screenshot I have attached, you can see several creature tokens that qualify for Evolve with Drone's entry but nothing happened.

### PR DESCRIPTION
**Pull request by tool4ever**
Refreshes active triggers before collecting, in line with
> 603.10. Normally, objects that exist immediately after an event are checked to see if the event matched any trigger conditions, and continuous effects that exist at that time are used to determine what the trigger conditions are and what the objects involved in the event look like.

For that to work with LTB trigger their registering has to be done after again (so they're not lost). This also means it's performed only once now for simultaneous zone change.

I tried to test a couple of basic scenarios and it seems to work...

Closes #5557

### CODE REVIEW

File: forge-game/src/main/java/forge/game/card/CardZoneTable.java [hunk 1]
```diff
@@ -63,11 +61,19 @@ public CardCollectionView getLastStateGraveyard() {
         return lastStateGraveyard;
     }
     public void setLastStateBattlefield(CardCollectionView lastState) {
-        // store it in a new object, it might be from Game which can also refresh itself
-        this.lastStateBattlefield = new CardCollection(lastState);
+        if (lastState == null) {
+            lastStateBattlefield = CardCollection.EMPTY;
+        } else {
+            // store it in a new object, it might be from Game which can also refresh itself
+            lastStateBattlefield = new CardCollection(lastState);
```
Comment (Hanmac) [inline forge-game/src/main/java/forge/game/card/CardZoneTable.java:68]: should this be short-style?

`lastStateBattlefield = lastState == null ? CardCollection.EMPTY : new CardCollection(lastState);`

**Review by Hanmac — APPROVED** [review]
