### PR TITLE
Performance: improve deduping

### LINKED ISSUE #2218: Jodah, the Unifier incorrectly asks you to choose card order
Jodah's second ability puts cards on the bottom of your library in a random order. The ability brought up the order-choosing box for me to stack the bottom.

### PR DESCRIPTION
**Pull request by tool4ever**
Really helps simulation more but doesn't hurt our old-school one either.

Gonna keep it Hand only on first iteration I think.

Closes #2218

### CODE REVIEW

File: forge-ai/src/main/java/forge/ai/ComputerUtilCard.java [hunk 1]
```diff
@@ -2052,6 +2052,25 @@ public static boolean isNonDisabledCardInPlay(final Player ai, final String card
         return false;
     }
 
+    public static CardCollection dedupeCards(CardCollection cc) {
+        CardCollection deduped = new CardCollection();
```
Comment (Hanmac) [inline forge-ai/src/main/java/forge/ai/ComputerUtilCard.java:2056]: maybe add a short cut if cc size <= 1, then it can just return cc?

**Review by kevlahnota — APPROVED** [review]
