### PR TITLE
Back to quest list button fix

### LINKED ISSUE #7307: [Adventure] Button "Quest List" doesn't work
**Describe the bug**
Button "Quest List" in quest description doesn't work in Adventure mode

**To Reproduce**
1. Open description of anyone quest
2. Tap "Quest List"

**Expected behavior**
Button "Quest List" should open list of quests, I think

**Additional context**

**Desktop:**
 - OS: Windows 10
 - Version: 2.0.03-SNAPSHOT-03.28

**Smartphone :**
 - OS: Android 11
 - Version: 2.0.03-SNAPSHOT-03.28

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by Eradev**
Fixes #7307

### CODE REVIEW

File: forge-gui-mobile/src/forge/adventure/scene/QuestLogScene.java [hunk 1]
```diff
@@ -77,8 +74,11 @@ private QuestLogScene() {
         ScrollPane scroller = new ScrollPane(scrollContainer);
         root.add(scroller).colspan(3).fill().expand();
 
-
-
+        backToListButton.addListener(new ClickListener() {
```
Comment (tool4ever) [inline forge-gui-mobile/src/forge/adventure/scene/QuestLogScene.java]: try keep logic together:
instead of adding second listener make the right adjustments via the `ui.onButtonPress` call above

Comment (Eradev) [reply forge-gui-mobile/src/forge/adventure/scene/QuestLogScene.java]: Can't use ui.onButtonPress as it doesn't exist in `quests.json`.

**Review by tool4ever — APPROVED** [review]
