### PR TITLE
fix 4812

### LINKED ISSUE #4812: Gyox, Brutal Carnivora crashes game
**Describe the bug**
Gyox, Brutal Carnivora

> At the beginning of your end step, put an oil counter on up to one target creature.
> 
> Whenever a nontoken creature you control with one or more oil counters on it dies, conjure X duplicates of it into exile, where X is the number of oil counters on it. Those duplicates perpetually get +X/+X. Then shuffle those duplicates into your library.

**To Reproduce**
1. Have Gyox, Brutal Carnivora in play
2. Put an oil counter on another creature
3. Let that creature die
4. Game crashes, see error below

**Screenshots**
Screenshot_20240309-112905

Screenshot_20240309-112855

Version:
Android 1.6.60-SNAPSHOT-03-08

### PR DESCRIPTION
**Pull request by Northmoc**
- closes #4812

### CODE REVIEW

File: forge-game/src/main/java/forge/game/Game.java [hunk 1]
```diff
@@ -712,6 +712,9 @@ public void forEachCardInGame(Visitor<Card> visitor, boolean withSideboard) {
             if (!visitor.visitAll(player.getInboundTokens())) {
                 return;
             }
+            if (!visitor.visitAll(player.getZone(ZoneType.None).getCards())) {
```
Comment (tool4ever) [inline forge-game/src/main/java/forge/game/Game.java:715]: this might cause all sorts of problems, let's not make None zone more real than it needs to be

File: forge-game/src/main/java/forge/game/card/Card.java [hunk 2]
```diff
@@ -7073,14 +7073,8 @@ public final boolean canBeSacrificedBy(final SpellAbility source, final boolean
...
     public final boolean canExiledBy(final SpellAbility source, final boolean effect) {
-        final Card gameCard = game.getCardState(this, null);
-        // gameCard is LKI in that case, the card is not in game anymore
-        // or the timestamp did change
-        // this should check Self too
-        if (gameCard == null || !this.equalsWithTimestamp(gameCard)) {
-            return false;
-        }
-
+        if (game.getCardState(this, null) == null) return false;
```
Comment (tool4ever) [inline forge-game/src/main/java/forge/game/card/Card.java:7076]: Imo for the reasons I outlined in the issue removing this check completely is the cleaner option

**Review by tool4ever — APPROVED** [review]
thanks, imo this is the safest fix
