### PR TITLE
AI: Various logic fixes and improvements

### LINKED ISSUE #3406: AI: Tempting Wurm
The AI doesn't use any strategy with Tempting Wurm. It should wait to cast it until the risk of their opponent dropping valuable stuff is reduced, say a hand size of 2 or less, or knowledge that the opponent's hand contains nothing that'll be of consequence.
image

### LINKED ISSUE #3407: AI: Grothama, All-Devouring
When asked whether to use a creature's "fight Grothama" ability, AI always responds "yes".

image

### LINKED ISSUE #3408: AI: Elderscale Wurm
AI doesn't consider whether Elderscale Wurm will prevent combat damage when assigning attackers.

image

### PR DESCRIPTION
**Pull request by Agetian**
Fixes #3406 
Fixes #3407 
Fixes #3408

Improves Banding AI vs. Trample.

### CODE REVIEW

File: forge-game/src/main/java/forge/game/player/Player.java [hunk 1]
```diff
@@ -799,7 +799,7 @@ public final int staticReplaceDamage(final int damage, final Card source, final
                     restDamage = 2;
                 }
             } else if (c.getName().equals("Elderscale Wurm")) {
-                if (c.getController().equals(this) && getLife() - restDamage < 7) {
+                if (c.getController().equals(this) && getLife() >= 7) {
                     restDamage = getLife() - 7;
```
Comment (tool4ever) [inline forge-game/src/main/java/forge/game/player/Player.java:803]: this change doesn't make sense:
if life is 20 and 10 damage would be dealt the prediction would now be raised to 13

File: forge-ai/src/main/java/forge/ai/SpecialCardAi.java [hunk 2]
```diff
@@ -651,6 +651,18 @@ public static boolean consider(final Player ai, final SpellAbility sa) {
         }
     }
 
+    // Grothama, All-Devouring
+    public static class GrothamaAllDevouring {
```
Comment (tool4ever) [inline forge-ai/src/main/java/forge/ai/SpecialCardAi.java:655]: Since it has pretty good stats I'm not sure AI should be just as eager to get rid of it for some draw if it controls it

Comment (Agetian) [reply forge-ai/src/main/java/forge/ai/SpecialCardAi.java:655]: Ah, true, I'll tweak that. You're referring to the case when the AI controls it and attacks with its own creatures, right?

Comment (Agetian) [reply forge-ai/src/main/java/forge/ai/SpecialCardAi.java:655]: In that case , I'm not even sure what a universally good condition would be for that, I think I'll just make the AI not agree to fight its own Grothama with its own creatures at all

File: forge-game/src/main/java/forge/game/player/Player.java (hunk 1 above)
Comment (Agetian) [reply forge-game/src/main/java/forge/game/player/Player.java]: Alrighty, tried to improve this prediction, though I admit that I suck at math, so I dunno :D

File: forge-ai/src/main/java/forge/ai/AiBlockController.java [hunk 3]
```diff
@@ -776,15 +772,44 @@ private void reinforceBlockersAgainstTrample(final Combat combat) {
                 continue;
             }
 
+            boolean needsMoreChumpBlockers = true;
+            // See if it's possible to tank up the damage with Banding
+            List<String> bandsWithString = Arrays.asList("Bands with Other Legendary Creatures",
```
Comment (tool4ever) [inline forge-ai/src/main/java/forge/ai/AiBlockController.java:777]: nice idea!
use `isValidBand` again?

File: forge-ai/src/main/java/forge/ai/AiBlockController.java [hunk 4]
```diff
@@ -776,15 +772,44 @@ private void reinforceBlockersAgainstTrample(final Combat combat) {
...
+                    "Bands with Other Creatures named Wolves of the Hunt",
+                    "Bands with Other Dinosaurs");
+            for (final Card blocker : combat.getBlockers(attacker)) {
+                if (blocker.hasKeyword(Keyword.BANDING) || blocker.hasAnyKeyword(bandsWithString)) {
+                    needsMoreChumpBlockers = false;
```
Comment (tool4ever) [inline forge-ai/src/main/java/forge/ai/AiBlockController.java:782]: This should just lead to `continue` so you avoid calculating `chumpBlockers` and don't need to have the first block if-enclosed

File: forge-ai/src/main/java/forge/ai/AiBlockController.java [hunk 5]
```diff
@@ -776,15 +772,44 @@ private void reinforceBlockersAgainstTrample(final Combat combat) {
                 continue;
```
Comment (tool4ever) [inline forge-ai/src/main/java/forge/ai/AiBlockController.java:772]: _Thorn Elemental_ ruling: 
> If blocked by a creature with banding, the defending player decides whether or not the damage is assigned “as though it weren’t blocked”. 

➡️ the part that checks for the static should be moved directly above the original block

Comment (Agetian) [reply forge-ai/src/main/java/forge/ai/AiBlockController.java:773]: Hmm, not sure if I completely understand how... Can you please clarify a little or help with this one?

File: forge-ai/src/main/java/forge/ai/AiBlockController.java (hunk 4 above)
Comment (Agetian) [reply forge-ai/src/main/java/forge/ai/AiBlockController.java]: Done :) :+1:

File: forge-ai/src/main/java/forge/ai/AiBlockController.java (hunk 5 above)
Comment (tool4ever) [reply forge-ai/src/main/java/forge/ai/AiBlockController.java:773]: banding still trumps in presence of that static
so it wouldn't be smart to skip completely if you can make it as a banding block

File: forge-gui/res/cardsfolder/t/tempting_wurm.txt [hunk 6]
```diff
@@ -6,4 +6,6 @@ T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.S
 SVar:EachOpponent:DB$ RepeatEach | RepeatPlayers$ Player.Opponent | RepeatSubAbility$ TemptingChange
 SVar:TemptingChange:DB$ ChangeZone | Origin$ Hand | Destination$ Battlefield | ChangeType$ Artifact,Creature,Enchantment,Land | DefinedPlayer$ Remembered | ChangeNum$ X
 SVar:X:Count$ValidHand Artifact.RememberedPlayerCtrl,Creature.RememberedPlayerCtrl,Enchantment.RememberedPlayerCtrl,Land.RememberedPlayerCtrl
+SVar:NeedsToPlayVar:Y LE2
```
Comment (schnautzr) [inline forge-gui/res/cardsfolder/t/tempting_wurm.txt:9]: Love it.

File: forge-ai/src/main/java/forge/ai/AiBlockController.java (hunk 4 above)
Comment (Agetian) [reply forge-ai/src/main/java/forge/ai/AiBlockController.java]: Done as well, thanks! :)

File: forge-ai/src/main/java/forge/ai/AiBlockController.java (hunk 5 above)
Comment (Agetian) [reply forge-ai/src/main/java/forge/ai/AiBlockController.java:774]: Alrighty, I tried something, but not sure if that's exactly how you wanted it :/

Comment (tool4ever) [reply forge-ai/src/main/java/forge/ai/AiBlockController.java:774]: Sure, I think I'll clean it up even more with a few other changes later

**Review by tool4ever — APPROVED** [review]
