### PR TITLE
AI: Account for transformable cards (e.g. Incubator tokens) when considering defenders

### LINKED ISSUE #3061: AI will always attack into non-transformed incubate tokens with open mana
**Describe the bug**
AI treats an incubate token with 2 open mana as if it's not there

**To Reproduce**
1. Give AI a 2/2. Create a 5/5 incubate token and two open mana.
2. AI will ignore the incubate token and attack into the open board.

**Expected behavior**
With 2 open mana AI ought to treat an incubate token as if it were transformed.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.6.57-SNAPSHOT-05.01

### PR DESCRIPTION
**Pull request by Agetian**
Fixes #3061 .

The code at AiAttackController.java:140-141 originally skipped all checks for tokens in this manner (probably for speed?) I currently made an exclusion to consider transformable tokens such as Incubator stuff, is that a viable solution? :/

### CODE REVIEW

**Comment by Agetian** [comment]
Will need to add a check if the transformed card is actually a creature , will do that after work.

File: forge-ai/src/main/java/forge/ai/AiAttackController.java [hunk 1]
```diff
@@ -152,6 +147,15 @@ public boolean apply(Card c) {
                     defenders.add(animatedCopy);
                 }
             }
+            // Transform (e.g. Incubator tokens)
+            for (SpellAbility sa : Iterables.filter(c.getSpellAbilities(), SpellAbilityPredicates.isApi(ApiType.SetState))) {
+                if ("Transform".equals(sa.getParam("Mode")) && ComputerUtilCost.canPayCost(sa, defender, false)
+                        && sa.getRestrictions().checkOtherRestrictions(c, sa, defender)) {
+                    Card transformedCopy = CardUtil.getLKICopy(c);
+                    transformedCopy.setState(CardStateName.Transformed, false);
+                    defenders.add(transformedCopy);
```
Comment (Hanmac) [inline forge-ai/src/main/java/forge/ai/AiAttackController.java:156]: might check if the transformed Copy is a creature?

Comment (Agetian) [reply forge-ai/src/main/java/forge/ai/AiAttackController.java:156]: Yup, going to add that after work 👍

Comment (Agetian) [reply forge-ai/src/main/java/forge/ai/AiAttackController.java]: Done :)

File: forge-ai/src/main/java/forge/ai/AiAttackController.java [hunk 2]
```diff
@@ -152,6 +147,17 @@ public boolean apply(Card c) {
                     defenders.add(animatedCopy);
                 }
             }
+            // Transform (e.g. Incubator tokens)
+            for (SpellAbility sa : Iterables.filter(c.getSpellAbilities(), SpellAbilityPredicates.isApi(ApiType.SetState))) {
```
Comment (tool4ever) [inline forge-ai/src/main/java/forge/ai/AiAttackController.java:151]: Looks like this code is pretty much `ComputerUtilCombat..canTransform?`

Comment (Agetian) [reply forge-ai/src/main/java/forge/ai/AiAttackController.java:151]: More or less, yes, but sadly, without iterating through spell abilities and grabbing the transform sa (with SetStateAPI) somehow, it'd be impossible to check if the AI can pay the cost for it :/ Do you have any ideas for how to implement that part seamlessly while simplifying the loop (e.g. by changing it into a canTransform check)?

File: forge-ai/src/main/java/forge/ai/AiAttackController.java [hunk 3]
```diff
@@ -142,7 +137,7 @@ public boolean apply(Card c) {
             }
         };
         for (Card c : CardLists.filter(defender.getCardsIn(ZoneType.Battlefield), canAnimate)) {
-            if (c.isToken() && c.getCopiedPermanent() == null) {
+            if (c.isToken() && c.getCopiedPermanent() == null && !c.canTransform(null)) {
```
Comment (tool4ever) [inline forge-ai/src/main/java/forge/ai/AiAttackController.java:140]: we might check if this logic is a bit outdated?
e.g. _Lita, Mechanical Engineer_ can create Vehicle token

File: forge-ai/src/main/java/forge/ai/AiAttackController.java (hunk 2 above)
Comment (Agetian) [reply forge-ai/src/main/java/forge/ai/AiAttackController.java:151]: I mean, we can check canTransform, and if it returns true, then loop over the SAs and find the SetState one and check the cost, but I'm not sure if that's much better than what it's currently doing :)

File: forge-ai/src/main/java/forge/ai/AiAttackController.java (hunk 3 above)
Comment (Agetian) [reply forge-ai/src/main/java/forge/ai/AiAttackController.java:140]: Yeah, I think maybe it's possible to remove it altogether?.. It was probably done for speed reasons originally though (checking it on hundreds of tokens in a token deck might be costly, I guess :) )

File: forge-ai/src/main/java/forge/ai/AiAttackController.java (hunk 2 above)
Comment (tool4ever) [reply forge-ai/src/main/java/forge/ai/AiAttackController.java:151]: It looks like it will check `canPayCost` too...?
Otherwise just returns the untransformed

Comment (tool4ever) [reply forge-ai/src/main/java/forge/ai/AiAttackController.java:151]: The only problem might be we don't add up the costs so the AI might expect a lot of defenders that are actually not possible

Comment (Agetian) [reply forge-ai/src/main/java/forge/ai/AiAttackController.java:151]: Yes, true, it's probably also true for other situations similar to this one where the AI weighs every case individually. Not sure how to make it account for all of them together off the top of my head tbh.

Comment (Agetian) [reply forge-ai/src/main/java/forge/ai/AiAttackController.java:151]: Hmm, maybe some trickery with remembering the mana sources necessary to pay every processed cost would be possible, but I'm not sure

File: forge-ai/src/main/java/forge/ai/AiAttackController.java (hunk 3 above)
Comment (Agetian) [reply forge-ai/src/main/java/forge/ai/AiAttackController.java:138]: Commented out this code for now, will test with it disabled from now on.

File: forge-ai/src/main/java/forge/ai/AiAttackController.java (hunk 2 above)
Comment (Agetian) [reply forge-ai/src/main/java/forge/ai/AiAttackController.java:150]: Checked the code for remembering and reserving mana sources, that's only implemented on the AI side (in the AI controller) and hooked up to AI-specific routines... Don't see a way to simulate that for the human opponent in order to determine how much can be paid :( There's probably a roundabout way where we can remember how much mana is already potentially spent (during the loop iteration) and then we bail out of adding defenders like that if we're above the total limit, it's going to be imprecise though.

Comment (Agetian) [reply forge-ai/src/main/java/forge/ai/AiAttackController.java:152]: Attempted what I mentioned above, it's imprecise but it sort of works for simple cases like Incubator where only colorless mana is used, I guess. I welcome any better implementation if you can think of one... This is prolly the best I can do for now. I wanted to also hook this up to Animate above, but I'm afraid that'll be a little bit too imprecise since many animate costs depend on particular color shards, and that'll make the thing fail more often than work vs. multicolor decks :/

Comment (Agetian) [reply forge-ai/src/main/java/forge/ai/AiAttackController.java:152]: I guess it'll also need to check if the cost actually has a mana part to avoid a NPE?

Comment (Agetian) [reply forge-ai/src/main/java/forge/ai/AiAttackController.java:152]: Maybe it can actually also be done for Animate... It'll miscount sometimes, I guess, but won't be as passive when not due? Prolly needs testing though.

Comment (Agetian) [reply forge-ai/src/main/java/forge/ai/AiAttackController.java:157]: After some tests, added this to Animate as well and added some NPE prevention. Probably the best I can do for now, I don't have any better ideas, sadly :)

File: forge-ai/src/main/java/forge/ai/AiAttackController.java (hunk 3 above)
Comment (Agetian) [reply forge-ai/src/main/java/forge/ai/AiAttackController.java:140]: So far, testing doesn't indicate any issues with this code commented out.

**Review by tool4ever — APPROVED** [review]
