### PR TITLE
Some cleanup

### LINKED ISSUE #8832: Jaws's triggered ability is wrong.
**Describe the bug**
Jaws, Relentless Predator's ability is working wrong.
This ability should trigger when Jaws deal damage to someone, but it's responding to all damage dealt by creatures I control.

**To Reproduce**
1. Attack with Jaws and creatures.
2. Deal combat damage to someone.
3. Jaws triggered multiple times.

**Expected behavior**
Triggers only when Jaws deal combat damage to someone.

**Screenshots**

Image

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version forge-installer-2.0.07-SNAPSHOT-10.03

### PR DESCRIPTION
**Pull request by tool4ever**
Closes #8832

### CODE REVIEW

**Review by Hanmac — APPROVED** [review]

File: forge-ai/src/main/java/forge/ai/ability/ChangeZoneAi.java [hunk 1]
```diff
@@ -765,6 +761,8 @@ protected boolean checkPhaseRestrictions(Player ai, SpellAbility sa, PhaseHandle
             return ph.getNextTurn().equals(ai) && ph.is(PhaseType.END_OF_TURN);
         } else if (aiLogic.equals("Main1") && ph.is(PhaseType.MAIN1, ai)) {
             return true;
+        } else if (aiLogic.equals("BeforeCombat")) {
+            return ai.getGame().getPhaseHandler().getPhase().isAfter(PhaseType.COMBAT_BEGIN);
```
Comment (CTimmerman) [inline forge-ai/src/main/java/forge/ai/ability/ChangeZoneAi.java:765]: Should this not be isBefore?

Comment (tool4ever) [reply forge-ai/src/main/java/forge/ai/ability/ChangeZoneAi.java:765]: right, good catch
