### PR TITLE
Fix Serialization exception

### LINKED ISSUE #9769: Abigale, Eloquent First Year, after resolve multiplayer game freezes
**Describe the bug**
When i play Abigale, Eloquent First Year, the game ask me to resolve it. I target the creature and the counters get applied. After this the server crashes in multiplayer. I do not have a prompt and my opponents do have a prompt. They can click as many times as they want on the ok button but nothing happens.

**To Reproduce**
1. play an multiplayer match.
2. play abigale.
3. target and resolve

**Expected behavior**
The opponents should be able to complete the prompt and continue play

**Screenshots**
dont have will add if i encounter it again

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: Forge 2.0.10-SNAPSHOT-02-12

### PR DESCRIPTION
**Pull request by tool4ever**
Closes #9769

### CODE REVIEW

**Comment by Hanmac** [comment]
Why un"record" it? Can we fix it as Record?

**Comment by mario026** [comment]
Reporter here, quick fix <3

**Comment by tool4ever** [comment]
@Hanmac
Records don't support transient fields

File: forge-game/src/main/java/forge/game/card/CounterKeywordType.java [hunk 1]
```diff
@@ -8,15 +8,22 @@
...
     // Rule 122.1b
     static ImmutableList<String> keywordCounter = ImmutableList.of(
             "Flying", "First Strike", "Double Strike", "Deathtouch", "Decayed", "Exalted", "Haste", "Hexproof",
             "Indestructible", "Lifelink", "Menace", "Reach", "Shadow", "Trample", "Vigilance");
     private static Map<String, CounterKeywordType> sMap = Maps.newHashMap();
 
-
     public static CounterKeywordType get(String s) {
         if (!sMap.containsKey(s)) {
             sMap.put(s, new CounterKeywordType(s, isKeywordCounter(s) ? Keyword.getInstance(s) : null));
```
Comment (Hanmac) [inline forge-game/src/main/java/forge/game/card/CounterKeywordType.java]: @tool4ever what if instead of whole Keyword, I just store the keyword title? 🤔

**Review by Hanmac — APPROVED** [review]
