### PR TITLE
Some fixes

### LINKED ISSUE #8805: Teyo, Geometric Tactician's -2 ability is not working.
**Describe the bug**
I activated Teyo, Geometric Tactician's -2 ability in Commander game, but distant AI attacked my planeswalker.

**To Reproduce**
1. activate Teyo, Geometric Tactician's -2 ability
2. pass turn to AI's turn
3. distant AI attack my planeswalker

**Expected behavior**
Only the player in the chosen direction can attack.

**Screenshots**
Image

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version forge-installer-2.0.07-SNAPSHOT-09.28

### PR DESCRIPTION
**Pull request by tool4ever**
Closes #8805

### CODE REVIEW

File: forge-ai/src/main/java/forge/ai/ability/CloneAi.java [hunk 1]
```diff
@@ -96,6 +96,10 @@ protected AiAbilityDecision doTriggerNoCost(Player aiPlayer, SpellAbility sa, bo
         if (sa.usesTargeting()) {
             chance = cloneTgtAI(sa);
         } else {
+            if (sa.isReplacementAbility() && host.isCloned()) {
```
Comment (Hanmac) [inline forge-ai/src/main/java/forge/ai/ability/CloneAi.java:99]: @tool4ever we probably need to debug how that happened

Comment (tool4ever) [reply forge-ai/src/main/java/forge/ai/ability/CloneAi.java:99]: no bug - it's not against the rules

Comment (Hanmac) [reply forge-ai/src/main/java/forge/ai/ability/CloneAi.java:99]: But what if the ability is mandatory?

Comment (tool4ever) [reply forge-ai/src/main/java/forge/ai/ability/CloneAi.java:99]: a mandatory RE wouldn't even get checked there
