### PR TITLE
Ai doesn't activate ability of deadeye duelist

### LINKED ISSUE #7476: AI doesn't activate ability of Deadeye Duelist
**Describe the bug**
AI doesn't activate ability of Deadeye Duelist even at the end of player's turn

**To Reproduce**
1. AI has 2 wastes and 2 Deadeye Duelist without summoning sickness
2. Player has 2 Spellskites with 2 +1/+1 counters on them
3. Players doesn't attack and pass
4. AI doesn't activate ability of Deadeye Duelist at the end of player's turn

**Expected behavior**
AI should activate ability of Deadeye Duelist at the end of player's turn if it has enough mana and and don't attack with it 

**Desktop:**
 - OS: Windows 10
 - Version: 2.0.03-SNAPSHOT-04.05

**Smartphone :**
 - OS: Android 11
 - Version: 2.0.03-SNAPSHOT-04.05

**Screenshots**

Image
Image

### PR DESCRIPTION
**Pull request by NathanRoy1**
Resolves #7476                                                                                                                                                                    

Deadeye Duelist has an activated ability ({1}, {T}: Deal 1 damage to target opponent) that the AI never used, except when the opponent was below 5 life.

Added a freePingPlayerOnly condition in DamageDealAi.java (damageChoosingTargets method) that allows the AI to fire activated abilities targeting only players at the end of the opponent's turn.

### CODE REVIEW

File: forge-ai/src/main/java/forge/ai/ability/DamageDealAi.java [hunk 1]
```diff
@@ -740,7 +740,12 @@ private boolean damageChoosingTargets(final Player ai, final SpellAbility sa, fi
                         || immediately) {
                     boolean pingAfterAttack = "PingAfterAttack".equals(logic) && phase.getPhase().isAfter(PhaseType.COMBAT_DECLARE_ATTACKERS) && phase.isPlayerTurn(ai);
                     boolean isPWAbility = sa.isPwAbility() && sa.getPayCosts().hasSpecificCostType(CostPutCounter.class);
-                    if (isPWAbility || (pingAfterAttack && !avoidTargetP(ai, sa)) || shouldTgtP(ai, sa, dmg, noPrevention)) {
+                    // Activated abilities that target only players (not creatures) should fire at end of opponent's turn
```
Comment (tool4ever) [inline forge-ai/src/main/java/forge/ai/ability/DamageDealAi.java]: looks to me like you could just pull this logic down to better clean it up:
https://github.com/Card-Forge/forge/blob/7971722ade0395d6eab6ff3fecd1212e0a9fdacd/forge-ai/src/main/java/forge/ai/ability/DamageDealAi.java#L680-L700

**Review by tool4ever — APPROVED** [review]
