### PR TITLE
Fix Conspiracy removing types without choice for new one

### LINKED ISSUE #5420: Kindred appears in the wrong order
Since the change from "Tribal" to "Kindred", the ordering of types on kindred cards has been incorrect. Hence, a card that should say "Kindred X" will say "Instant Kindred", "Enchantment Kindred", "Artifact Kindred", etc.

### PR DESCRIPTION
**Pull request by tool4ever**
I also changed it so it avoids adding empty traits in this case.

Closes #5420

### CODE REVIEW

File: forge-game/src/main/java/forge/game/staticability/StaticAbilityContinuous.java [hunk 1]
```diff
@@ -422,26 +422,30 @@ public static CardCollectionView applyContinuousAbility(final StaticAbility stAb
...
-                remove.add(RemoveType.CreatureTypes);
-            }
-            if (params.containsKey("RemoveArtifactTypes")) {
-                remove.add(RemoveType.ArtifactTypes);
-            }
-            if (params.containsKey("RemoveEnchantmentTypes")) {
-                remove.add(RemoveType.EnchantmentTypes);
+
+            // overwrite doesn't work without new value (e.g. Conspiracy missing choice)
+            if (addTypes == null || !addTypes.isEmpty()) {
```
Comment (Hanmac) [inline forge-game/src/main/java/forge/game/staticability/StaticAbilityContinuous.java:427]: Isn't this wrong? What if something would just remove types without adding them? Wouldn't that break now?

Comment (tool4ever) [reply forge-game/src/main/java/forge/game/staticability/StaticAbilityContinuous.java:427]: if it would only remove and not overwrite like _Alpine Moon_ addTypes will be null

Comment (Hanmac) [reply forge-game/src/main/java/forge/game/staticability/StaticAbilityContinuous.java:427]: Hm, I somehow don't like the difference between `addTypes` not used, and `addTypes` being empty 🤔

**Review by Hanmac — APPROVED** [review]
