### PR TITLE
fix crashes issue4472

### LINKED ISSUE #4472: Card.fromPaperCard crashes on a specialize face
**Describe the bug**
A MakeCard effect with "Name$ ChosenName" causes Forge to crash if the ChosenName is one of faces of a specialize card.

**To Reproduce**
1. Begin a Vanguard match using Maelstrom Archangel Avatar
2. Attack and deal combat damage with either Gut, Devious Fanatic or Gut, Zealous Fanatic (as both of these specialize faces have unique mana costs not found on any other card)
3. At end of combat, Maelstrom Archangel Avatar triggers; as your attacker is the only card with its mana cost, the randomly-chosen card with that cost will be another copy of the same card
4. Forge crashes

**Expected behavior**
The token should be created without the game crashing.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.6.60-SNAPSHOT-01-02

**Additional context**
Crash log:
`java.lang.NullPointerException: Cannot invoke "forge.item.IPaperCard.getRules()" because "cp" is null
	at forge.game.card.CardFactory.getCard(CardFactory.java:223)
	at forge.game.card.CardFactory.getCard(CardFactory.java:220)
	at forge.game.card.Card.fromPaperCard(Card.java:7139)
	at forge.game.ability.effects.MakeCardEffect.resolve(MakeCardEffect.java:133)
	at forge.game.spellability.AbilitySub.resolve(AbilitySub.java:105)
	at forge.game.ability.AbilityUtils.resolveApiAbility(AbilityUtils.java:1454)
	at forge.game.ability.AbilityUtils.resolveSubAbilities(AbilityUtils.java:1438)
	at forge.game.ability.AbilityUtils.resolveApiAbility(AbilityUtils.java:1460)
	at forge.game.ability.AbilityUtils.resolve(AbilityUtils.java:1422)
	at forge.game.ability.effects.RepeatEachEffect.resolve(RepeatEachEffect.java:109)
	at forge.game.spellability.AbilitySub.resolve(AbilitySub.java:105)
	at forge.game.ability.AbilityUtils.resolveApiAbility(AbilityUtils.java:1454)
	at forge.game.ability.AbilityUtils.resolve(AbilityUtils.java:1422)
	at forge.player.HumanPlaySpellAbility.playAbility(HumanPlaySpellAbility.java:193)
	at forge.player.HumanPlay.playSpellAbilityNoStack(HumanPlay.java:180)
	at forge.player.PlayerControllerHuman.playSpellAbilityNoStack(PlayerControllerHuman.java:325)
	at forge.game.trigger.WrappedAbility.resolve(WrappedAbility.java:493)
	at forge.game.ability.AbilityUtils.resolveApiAbility(AbilityUtils.java:1454)
	at forge.game.ability.AbilityUtils.resolve(AbilityUtils.java:1422)
	at forge.game.zone.MagicStack.resolveStack(MagicStack.java:553)
	at forge.game.phase.PhaseHandler.startFirstTurn(PhaseHandler.java:1152)
	at forge.game.GameAction.startGame(GameAction.java:2106)
	at forge.game.Match.startGame(Match.java:90)
	at forge.gamemodes.match.HostedMatch$2.run(HostedMatch.java:255)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)`
This crash also occurs when attempting to add a specialized face to the game directly via the dev tools, or when choosing a specialize face for Killer Cosplay. While testing, I found a non-crash oddity as well: choosing the back face of a dual-faced card (modal or transforming) for Killer Cosplay causes the choose-card-name menu to pop up again until you choose one that isn't a back face.

### PR DESCRIPTION
**Pull request by Northmoc**
I think this should close #4472 

 - now you can add specialize faces to battlefield through Dev cheats
 -  In the issue's corner case with that Maelstrom Archangel Avatar Vanguard + the specialize face now Forge will spit out a non-specialized version of the card. Is that legal/correct? I'm sure we'll never know since this combines Alchemy and Vanguard. I'm not convinced that the Maelstrom Archangel Avatar should find a mana cost match at all.
 - seems like the CardDb code also makes loading the proper art for each specialize face work now

### CODE REVIEW

File: forge-core/src/main/java/forge/card/CardDb.java [hunk 1]
```diff
@@ -433,6 +433,14 @@ public void addCard(PaperCard paperCard) {
...
             allCardsByName.put(paperCard.getRules().getMainPart().getName(), paperCard);
         }
+        if (paperCard.getRules().getSplitType() == CardSplitType.Specialize) {
+            //also include specialize faces
+            allCardsByName.put(paperCard.getRules().getWSpecialize().getName(), paperCard);
+            allCardsByName.put(paperCard.getRules().getUSpecialize().getName(), paperCard);
+            allCardsByName.put(paperCard.getRules().getBSpecialize().getName(), paperCard);
+            allCardsByName.put(paperCard.getRules().getRSpecialize().getName(), paperCard);
+            allCardsByName.put(paperCard.getRules().getGSpecialize().getName(), paperCard);
+        }
```
Comment (Hanmac) [inline forge-core/src/main/java/forge/card/CardDb.java:443]: use `getSpecializeParts` or `getAllFaces` to get all the names?

File: forge-gui/src/main/java/forge/player/PlayerControllerHuman.java [hunk 2]
```diff
@@ -2849,10 +2850,24 @@ private void addCardToZone(ZoneType zone, final boolean repeatLast, final boolea
...
+                                forgeCard.changeToState(CardStateName.SpecializeW);
+                            } else if (f.getName().equals(forgeCard.getState(CardStateName.SpecializeU).getName())) {
+                                forgeCard.changeToState(CardStateName.SpecializeU);
+                            } else if (f.getName().equals(forgeCard.getState(CardStateName.SpecializeB).getName())) {
+                                forgeCard.changeToState(CardStateName.SpecializeB);
+                            } else if (f.getName().equals(forgeCard.getState(CardStateName.SpecializeR).getName())) {
+                                forgeCard.changeToState(CardStateName.SpecializeR);
+                            } else if (f.getName().equals(forgeCard.getState(CardStateName.SpecializeG).getName())) {
+                                forgeCard.changeToState(CardStateName.SpecializeG);
+                            }
```
Comment (Hanmac) [inline forge-gui/src/main/java/forge/player/PlayerControllerHuman.java:2864]: `getSpecializeParts()` would give you a better map to iterate over all the CardStates and CardFaces

**Review by Hanmac — APPROVED** [review]
