### PR TITLE
Basic AI for Gale's Redirection, Consecrate // Consume, Serra's Emissary

### LINKED ISSUE #500: AI Logic for Gale's Redirection
Hmm, I don't remember anything already in ChangeZoneAi in particular, it'll probably need a hook to a standard counter logic (along the lines of "if AILogic is set to CounterSpell, then run a check for the counter logic and, if it succeeds, agree to play the spell targeting whatever is on the stack"). Might look into in but need a little bit more time than currently available... :/

_Originally posted by @Agetian in https://github.com/Card-Forge/forge/pull/486#discussion_r881219875_

### LINKED ISSUE #3370: Consecrate // Consume probably missing A.I. logic
**Describe the bug**
Opponent cast Consume targeting me. I have zero creatures on the field, whereas each of the other opponents have at least one. The card will do literally nothing here.

**Expected behavior**
To at least cast the spell targeting a player with a creature to sacrifice.

Screenshot_20230630_012256

### LINKED ISSUE #3378: When asked to 'choose a card type', AI chooses poorly
This is the first time I've seen the AI play this card and I haven't tested to see if this happens every time, but my AI opponent cast a Serra's Emissary and chose to have protection from schemes. There were no schemes in play

image

### PR DESCRIPTION
**Pull request by Agetian**
Fixes #500 
Fixes #3370 
Fixes #3378 when it comes to Serra's Adversary (can definitely use further AI logic improvements for ChooseType in general)

### CODE REVIEW

File: forge-ai/src/main/java/forge/ai/ability/ChangeZoneAi.java [hunk 1]
```diff
@@ -2075,6 +2078,35 @@ public boolean apply(Card card) {
...
+            SpellAbility topSA = top.getSpellAbility(false);
+            if (topSA != null) {
+                if (topSA.getPayCosts().hasManaCost()) {
+                    manaCost = topSA.getPayCosts().getTotalMana().getCMC();
+                }
+
+                if ((manaCost >= minCost || dangerousAPI.contains(topSA.getApi()))
+                        && topSA.getActivatingPlayer().isOpponentOf(aiPlayer)
+                        && sa.canTargetSpellAbility(topSA)) {
+                    sa.getTargets().add(topSA);
```
Comment (tool4ever) [inline forge-ai/src/main/java/forge/ai/ability/ChangeZoneAi.java:2102]: doesn't it need resetTargets or it will always fail if it can't pay on first try?

Comment (Agetian) [reply forge-ai/src/main/java/forge/ai/ability/ChangeZoneAi.java:2103]: Yep, good catch! :)

**Review by tool4ever — APPROVED** [review]
