### PR TITLE
Basic implementation for targeted Suspect AI (Nelly Borca)

### LINKED ISSUE #9223: Nelly Borca AI Missing Attack Trigger
**Describe the bug**
Playing against the AI, Nelly Borca doesnt have her attack trigger

**To Reproduce**
Witnessed in a game against the Nelly Borca Precon, let borca attack

**Expected behavior**
Borca should have a trigger to suspect a creature, it isn't an optional ability

**Desktop (please complete the following information):**
 - OS: MacOs
 - Version Daily Snapshot

### PR DESCRIPTION
**Pull request by Agetian**
Tricky ability, so can definitely be improved later.
Fixes #9223

### CODE REVIEW

File: forge-ai/src/main/java/forge/ai/ability/AlterAttributeAi.java [hunk 1]
```diff
@@ -26,6 +31,25 @@ protected AiAbilityDecision checkApiLogic(Player aiPlayer, SpellAbility sa) {
...
+                switch (attr.trim()) {
+                    case "Suspect":
+                    case "Suspected":
+                        // below, Suspected is treated as better, so target own beefy stuff for now to give it Menace
+                        CardCollection creaturesOTB = aiPlayer.getCreaturesInPlay();
+                        if (!creaturesOTB.isEmpty()) {
+                            Card bestTgt = ComputerUtilCard.getBestAI(CardLists.filter(creaturesOTB,
+                                    CardPredicates.hasKeyword(Keyword.MENACE).negate()));
+                            if (bestTgt == null) {
+                                bestTgt = ComputerUtilCard.getBestAI(aiPlayer.getCreaturesInPlay());
```
Comment (tool4ever) [inline forge-ai/src/main/java/forge/ai/ability/AlterAttributeAi.java]: should use `getTargetableCards`

Comment (tool4ever) [reply forge-ai/src/main/java/forge/ai/ability/AlterAttributeAi.java]: it still needs to find a target even if it's from another player...

Comment (Agetian) [reply forge-ai/src/main/java/forge/ai/ability/AlterAttributeAi.java]: Good call, tried to make the search more comprehensive :+1:

**Review by tool4ever — APPROVED** [review]
