### PR TITLE
Villanous choice initial implementation

### LINKED ISSUE #3926: WHO Face a Villainous Choice
> 701.53. [Face a Villainous Choice](https://mtg.fandom.com/wiki/Face_a_villainous_choice)
        701.53a “[A player] faces a villainous choice — [option A], or [option B]” means “[A player] chooses [option A] or [option B]. Then all actions in the chosen option are performed.”
        701.53b While facing a villainous choice, a player may choose an option that is illegal or impossible. In that case, they perform as much of the action as is possible. This is an exception to rule 608.2d.
        701.53c A replacement effect may replace an instruction to face a villainous choice with an instruction to face that choice some number of additional times. In that case, the entire process described in rule 701.53a is performed for that player the appropriate number of times one at a time.
        701.53d If more than one player is instructed to face a villainous choice, the entire process described in rule 701.53a is performed for each of those players one at a time in APNAP order. This is an exception to rule 608.2e.

similar to GenericChoice , but because of the exceptions, (and replacement effects)

 The Valeyard has this:
> If an opponent would face a villainous choice, they face that choice an additional time.

### PR DESCRIPTION
**Pull request by tehdiplomat**
Closes #3926

### CODE REVIEW

**Comment by Hanmac** [comment]
as for The Valeyard, i would probably use an Replacement Effect for this that updates the Num

**Comment by tehdiplomat** [comment]
Yea I probably won't have time to finish it. Realized my sister is in town in a few days and i need to get my house clean. I just did it this way, since thats what we did for voting.

File: forge-game/src/main/java/forge/game/ability/effects/VillainousChoiceEffect.java [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+
+            // For the AI chooseSAForEffect really should take the least good ability. Currently it just takes the first
+            List<SpellAbility> chosenSAs = Lists.newArrayList();
+            for(int i = 0; i < choiceAmount; i++) {
+                // This is a loop because you can choose the same abilities multiple times
+                 chosenSAs.addAll(p.getController().chooseSpellAbilitiesForEffect(abilities, sa, prompt, amount, ImmutableMap.of()));
+            }
+
+            for (SpellAbility chosenSA : chosenSAs) {
+                AbilityUtils.resolve(chosenSA);
```
Comment (Hanmac) [inline forge-game/src/main/java/forge/game/ability/effects/VillainousChoiceEffect.java:40]: if multiple players face Villainous Choices, the spell Ability probably needs to remember the player p

File: forge-game/src/main/java/forge/game/ability/effects/VillainousChoiceEffect.java [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+
+public class VillainousChoiceEffect extends SpellAbilityEffect {
+    @Override
+    public void resolve(SpellAbility sa) {
+        final List<SpellAbility> abilities = Lists.newArrayList(sa.getAdditionalAbilityList("Choices"));
+        final int amount = extractAmount(sa);
+        String prompt = sa.getParamOrDefault("ChoicePrompt", "Villainous Choice by " + sa.getActivatingPlayer());
+
+        for (Player p : getDefinedPlayersOrTargeted(sa)) {
+            int choiceAmount = p.getAdditionalVillainousChoices() + 1;
```
Comment (tool4ever) [inline forge-game/src/main/java/forge/game/ability/effects/VillainousChoiceEffect.java:21]: I think with the Valeyard wording it's not linear like the voting 🤔 
but instead if you control this twice it would go from 1->2->4
so probably `2^p.getAdditionalVillainousChoices()`?

Comment (Hanmac) [reply forge-game/src/main/java/forge/game/ability/effects/VillainousChoiceEffect.java:21]: I would prefer to use Replacement Effects for this, but I will check that out later

File: forge-game/src/main/java/forge/game/ability/effects/VillainousChoiceEffect.java (hunk 1 above)
Comment (tehdiplomat) [reply forge-game/src/main/java/forge/game/ability/effects/VillainousChoiceEffect.java:45]: Yea i hadn't added that because i didn't quite add the cards that required it. One card in now that does.

File: forge-game/src/main/java/forge/game/ability/effects/VillainousChoiceEffect.java (hunk 2 above)
Comment (tehdiplomat) [reply forge-game/src/main/java/forge/game/ability/effects/VillainousChoiceEffect.java:23]: If thats what the math is supposed to be I'm happy to switch it, I didn't see that in the faq anywhere?

File: forge-gui/res/tokenscripts/b_a_3_3_dalek_menace.txt [hunk 3]
```diff
@@ -0,0 +1,7 @@
+Name:Dalek
+ManaCost:no cost
+Types:Artifact Creature Dalek
+PT:3/3
+Colors:black
+K:Menace
+Oracle:Menahce
```
Comment (Simisays) [inline forge-gui/res/tokenscripts/b_a_3_3_dalek_menace.txt:7]: typo

File: forge-gui/res/cardsfolder/d/davros_dalek_creator.txt [hunk 4]
```diff
@@ -0,0 +1,12 @@
+Name:Davros, Dalek Creator
+ManaCost:1 U B R
+Types:Legendary Artifact Creature Alien Scientist
+PT:3/4
+K:Menace
+T:Mode$ Phase | Phase$ End of Turn | ValidPlayer$ You | TriggerZones$ Battlefield | Execute$ DalekCreation | TriggerDescription$ At the beginning of your end step, create a 3/3 black Dalek artifact creature token with menace if an opponent lost 3 or more life this turn. Then each opponent who lost 3 or more life this turn faces a villainous choice — You draw a card, or that player discards a card.
+SVar:DalekCreation:DB$ Token | TokenAmount$ 1 | TokenScript$ b_a_3_3_dalek_menace | TokenOwner$ You | ConditionCheckSVar$ X | ConditionSVarCompare$ GE3 | SubAbility$ VillainousChoice
+SVar:VillainousChoice:DB$ VillainousChoice | Defined$ Player.LostLifeThisTurn GE3 | Choices$ Draw,Discard
```
Comment (tool4ever) [inline forge-gui/res/cardsfolder/d/davros_dalek_creator.txt:8]: `Defined$ Opponent.`

File: forge-game/src/main/java/forge/game/ability/effects/VillainousChoiceEffect.java (hunk 2 above)
Comment (tool4ever) [reply forge-game/src/main/java/forge/game/ability/effects/VillainousChoiceEffect.java:23]: yea I asked judges and have been proven wrong 🍌

**Review by tool4ever — APPROVED** [review]
