### PR TITLE
Fix incomplete replacement caching leading to StackOverflow

### LINKED ISSUE #2749: StackOverflow from Master Chef Replacement
Because the static is not connected to a KW the card will always get a new RE (with different ID)

1. Reverting https://github.com/Card-Forge/forge/pull/2449/commits/4734b02c0 works

2. another way would be doing ``newCopy.setStoredReplacementEffects(in.getStoredReplacementEffects())`` in `getLKICopy` and then also later when the Affected is updated

### PR DESCRIPTION
**Pull request by tool4ever**
Closes #2749

### CODE REVIEW

File: forge-game/src/main/java/forge/game/card/Card.java [hunk 1]
```diff
@@ -4571,7 +4582,28 @@ public Table<Long, String, KeywordInterface> getStoredKeywords() {
...
+            if (lki) {
+                for (Table.Cell<Long, Long, KeywordsChange> kwCell : changedCardKeywords.cellSet()) {
+                    // same static
+                    if (kwCell.getColumnKey().equals(c.getRowKey())) {
+                        for (KeywordInterface kw : kwCell.getValue().getKeywords()) {
+                            // same kw
+                            if (kw.getOriginal().equals(c.getValue().getOriginal())) {
+                                stored = kw;
+                            }
+                        }
```
Comment (Hanmac) [inline forge-game/src/main/java/forge/game/card/Card.java:4597]: i don't think that is always true what if the card would give multiple instances of the same keyword?

Comment (tool4ever) [reply forge-game/src/main/java/forge/game/card/Card.java:4597]: L4591 does check that the static IDs are same too

I mean otherwise ``getKeywordForStaticAbility()`` would have a problem too?

**Review by kevlahnota — APPROVED** [review]
