### PR TITLE
Cleanup fixes

### LINKED ISSUE #3886: Immobilizer Eldrazi rulings not correctly applied
**Describe the bug**
According to the [rulings](https://gatherer.wizards.com/pages/card/Details.aspx?multiverseid=407607) `Immobilizer Eldrazi`'s ability should check for power and toughness when you declare blockers however it seems to check it as the ability resolves.

**To Reproduce**
1. Begin the puzzle `Perplexing Chimera (GatheringMagic.com) 012616 - Sucker Punch`
2. You should be in the attack phase of your opponent
3. During the attack phase of your opponent do the following:
      a. Cast `Sweep Away` using `1UR` targetting opponent's attacking `Mountain` and choosing to put it into their library.
      b. Cast `Dimensional Infiltrator` using `U`. Before it resolves cast `Abstruse Interference` using `U` and `Hedron Crawler`'s ability targetting the `Dimensional Infiltrator`.
      c. Let `Kozilek's Sentinel` trigger resolve so it becomes a `2/4`.
      d. Let `Abstruse Interference` resolve but pay `R` so `Dimensional Infiltrator` doesn't get counter.
      e. Let `Kozilek's Sentinel` trigger resolve so it becomes a `3/4`.
      f. Finally let `Dimensional Infiltrator` resolve.
      g. Using `R` and `Cultivator Drone`'s ability, activate `Dimensional Infiltrator`'s ability. The card on top of your opponent's library is a `Mountain` and we can return `Dimensional Infiltrator` to our hand.
      h. Finally, cast `Dimensional Infiltrator` again and let everything resolve. Your `Kozilek's Sentinel` should now be a `4/4`.
4. Move to the `Declare Blockers` phase and try to block any creature with `Kozilek's Sentinel`.
5. `Kozilek's Sentinel` is not able to block any creature.

**Expected behavior**
`Kozilek's Sentinel` is now a `4/4` and should be able to block even though it was a `1/4` when `Immobilizer Eldrazi`'s ability was activated.

**Desktop**
 - OS: MacOs
 - Browser: chrome (not sure why this matters)
 - Version: mtg forge 1.6.59

**Additional context**
I assume there are many ways to hit this issue, I just found it during the puzzle.

### PR DESCRIPTION
**Pull request by tool4ever**
- Closes #3886

- Fix _Vodalian War Machine_ trigger not counting Merfolk if its abilities get countered

### CODE REVIEW

File: forge-gui/src/main/java/forge/player/PlayerControllerHuman.java [hunk 1]
```diff
@@ -448,11 +448,12 @@ public Integer announceRequirements(final SpellAbility ability, final String ann
         boolean canChooseZero = true;
         Cost cost = ability.getPayCosts();
 
+        if (ability.hasParam("XMaxLimit")) {
```
Comment (Hanmac) [inline forge-gui/src/main/java/forge/player/PlayerControllerHuman.java:451]: XMaxLimit should only apply when announce = X ?

File: forge-gui/res/cardsfolder/i/immobilizer_eldrazi.txt [hunk 2]
```diff
@@ -3,6 +3,7 @@ ManaCost:1 R
 Types:Creature Eldrazi Drone
 PT:2/1
 K:Devoid
-A:AB$ PumpAll | Cost$ 2 C | ValidCards$ Creature.powerLTtoughness | KW$ HIDDEN CARDNAME can't block. | SpellDescription$ Each creature with toughness greater than its power can't block this turn.
```
Comment (Hanmac) [inline forge-gui/res/cardsfolder/i/immobilizer_eldrazi.txt:6]: `HIDDEN CARDNAME can't block.` needs to be removed from other cards too

Comment (tool4ever) [reply forge-gui/res/cardsfolder/i/immobilizer_eldrazi.txt:6]: I know but too many for now especially since AI logic depends on it

File: forge-gui/src/main/java/forge/player/PlayerControllerHuman.java (hunk 1 above)
Comment (tool4ever) [reply forge-gui/src/main/java/forge/player/PlayerControllerHuman.java:451]: Hmn, I kind of wanted to avoid the extra code for _Tranquil Frillback_
Don't think it's possible for another Announce to get mixed there? 🤔

Comment (Hanmac) [reply forge-gui/src/main/java/forge/player/PlayerControllerHuman.java:451]: it might be confusing to use XMaxLimit for something not named X

File: forge-gui/res/cardsfolder/e/elvish_vatkeeper.txt [hunk 3]
```diff
@@ -5,7 +5,7 @@ PT:3/3
 T:Mode$ ChangesZone | Origin$ Any | Destination$ Battlefield | ValidCard$ Card.Self | Execute$ TrigIncubate | TriggerDescription$ When CARDNAME enters the battlefield, incubate 2. (Create an Incubator token with two +1/+1 counters on it and "{2}: Transform this artifact." It transforms into a 0/0 Phyrexian artifact creature.)
 SVar:TrigIncubate:DB$ Incubate | Amount$ 2
 A:AB$ SetState | Cost$ 5 | TgtPrompt$ Select target Incubator token you control | ValidTgts$ Incubator.token+YouCtrl | Mode$ Transform | SubAbility$ DBDouble | SpellDescription$ Transform target Incubator token you control.
-SVar:DBDouble:DB$ MultiplyCounter | Defined$ Targeted | CounterType$ P1P1 | SpellDescription$ SpellDescription | SpellDescription$ Double the number of +1/+1 counters on it.
+SVar:DBDouble:DB$ MultiplyCounter | Defined$ Targeted | CounterType$ P1P1 | SpellDescription$ Double the number of +1/+1 counters on it.
```
Comment (Northmoc) [inline forge-gui/res/cardsfolder/e/elvish_vatkeeper.txt:8]: probably `StackDescription$ SpellDescription` was what it was supposed to be

File: forge-gui/src/main/java/forge/player/PlayerControllerHuman.java (hunk 1 above)
Comment (Northmoc) [reply forge-gui/src/main/java/forge/player/PlayerControllerHuman.java:451]: Yes, seems this would work. The param name is just a bit unintuitive

File: forge-gui/res/cardsfolder/upcoming/tempest_hart_scan_the_clouds.txt [hunk 4]
```diff
@@ -14,6 +14,6 @@ ALTERNATE
 Name:Scan the Clouds
 ManaCost:1 U
 Types:Instant  Adventure
```
Comment (Northmoc) [inline forge-gui/res/cardsfolder/upcoming/tempest_hart_scan_the_clouds.txt:16]: looks like a spacing issue here too

File: forge-gui/res/cardsfolder/v/vodalian_war_machine.txt [hunk 5]
```diff
@@ -3,9 +3,11 @@ ManaCost:1 U U
 Types:Creature Wall
 PT:0/4
 K:Defender
-A:AB$ Effect | Cost$ tapXType<1/Merfolk> | RememberCostCards$ True | StaticAbilities$ CanAttack | SpellDescription$ CARDNAME can attack this turn as though it didn't have defender.
+T:Mode$ AbilityCast | ValidCard$ Card.Self | Static$ True | Execute$ TrigStore
+SVar:TrigStore:DB$ Pump | RememberObjects$ TriggeredSpellAbility>TappedCards
```
Comment (Northmoc) [inline forge-gui/res/cardsfolder/v/vodalian_war_machine.txt:7]: shouldn't it also forget at end of turn?

Say you activate some abilities on your turn, then on opponent's turn they kill the VWM... in this case it would destroy the tapped merfolk even though they weren't tapped "this turn", right?

File: forge-gui/res/cardsfolder/e/elvish_vatkeeper.txt (hunk 3 above)
Comment (tool4ever) [reply forge-gui/res/cardsfolder/e/elvish_vatkeeper.txt:8]: I checked and the autobuilt looked fine

File: forge-gui/res/cardsfolder/v/vodalian_war_machine.txt (hunk 5 above)
Comment (tool4ever) [reply forge-gui/res/cardsfolder/v/vodalian_war_machine.txt:7]: it has static phase cleanup trigger (still problematic but it is what it is)

Comment (Northmoc) [reply forge-gui/res/cardsfolder/v/vodalian_war_machine.txt:7]: heh, I just missed that in the soup

File: forge-gui/res/cardsfolder/i/immobilizer_eldrazi.txt (hunk 2 above)
Comment (Agetian) [reply forge-gui/res/cardsfolder/i/immobilizer_eldrazi.txt:6]: Yeah, CARDNAME can't block is a tricky case (as outlined in #3790) - the AI can only detect inability to block through this pseudo-keyword. The (proper?) static ability application of can't block currently causes issues for the AI that I haven't yet found a way to resolve. Changing all the cards to a CantBlock static will require a certain rework of the AI since otherwise it'll break AI determining whether something can or can't block completely.

Comment (Agetian) [reply forge-gui/res/cardsfolder/i/immobilizer_eldrazi.txt:6]: (Addendum: assistance is definitely needed with that, as I've tried a few different things in the past but none of them did the trick :/ )

File: forge-gui/src/main/java/forge/player/PlayerControllerHuman.java (hunk 1 above)
Comment (tool4ever) [reply forge-gui/src/main/java/forge/player/PlayerControllerHuman.java:451]: Alright, guess I'll just switch back to the previous solution to be on the safe side
no big deal anyway

**Review by Agetian — APPROVED** [review]
