### PR TITLE
Fix Old-Growth Troll

### LINKED ISSUE #7395: Refactor attachAuraOnIndirectEnterBattlefield and remove getFirstAttachSpell
Refactor `attachAuraOnIndirectEnterBattlefield`
because cards like `Old-Growth Troll` might enter indirect with Enchant Keyword but without Aura Spell
`attachAuraOnIndirectEnterBattlefield` might need EmptySA for `chooseSingleEntityForEffect`

Maybe even remove `getFirstAttachSpell` because it might not be needed?

### PR DESCRIPTION
**Pull request by tool4ever**
Closes #7395

### CODE REVIEW

File: forge-game/src/main/java/forge/game/GameAction.java [hunk 1]
```diff
@@ -2773,19 +2771,18 @@ public void completeDungeon(Player player, Card dungeon) {
...
+        // When an Aura ETB without being cast you can choose a valid card to attach it to
         if (!source.hasKeyword(Keyword.ENCHANT)) {
             return false;
         }
 
+        SpellAbility aura = source.getFirstAttachSpell();
         if (aura == null) {
-            return false;
+            // if it's not normally an aura
+            aura = new SpellAbility.EmptySa(ApiType.Attach, source);
```
Comment (Hanmac) [inline forge-game/src/main/java/forge/game/GameAction.java:2783]: Add these SVars from source to Fake-Aura?
https://github.com/Card-Forge/forge/blob/b4af62eda71d1892ce4e13b3bf8adbda1f398f8c/forge-game/src/main/java/forge/game/card/CardFactory.java#L459-L467

**Comment by Hanmac** [comment]
I will remove the last pieces of `getFirstAttachSpell` later with a different MR

**Review by Hanmac — APPROVED** [review]

**Review by Hanmac — APPROVED** [review]
