### PR TITLE
Fix voting crash

### LINKED ISSUE #8324: Vote breaks NetPlay
```
io.netty.handler.codec.EncoderException: java.io.NotSerializableException: forge.game.ability.effects.InvestigateEffect
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
```

Caused by #8286

### PR DESCRIPTION
**Pull request by tool4ever**
Closes #8324

### CODE REVIEW

**Comment by Hanmac** [comment]
so it did crash for Player/Card too? i thought i didn't changed that?

and you forgot to tag me, thats why i did this: #8331

File: forge-gui/src/main/java/forge/player/PlayerControllerHuman.java [hunk 1]
```diff
@@ -1463,10 +1463,10 @@ public String chooseRollSwapValue(List<String> swapChoices, Integer currentResul
     @Override
     public Object vote(final SpellAbility sa, final String prompt, final List<Object> options,
                        final ListMultimap<Object, Player> votes, Player forPlayer, boolean optional) {
-        if (optional) {
-            return getGui().oneOrNone(prompt, options);
+        if (options.get(0) instanceof SpellAbility) {
+            return chooseSpellAbilitiesForEffect((List<SpellAbility>)(Object) options, sa, prompt, 1, null).get(0);
```
Comment (Hanmac) [inline forge-gui/src/main/java/forge/player/PlayerControllerHuman.java]: this doesn't respect the optional param

Comment (tool4ever) [reply forge-gui/src/main/java/forge/player/PlayerControllerHuman.java]: it's only used once for Cards so I didn't bother there

**Comment by tool4ever** [comment]
> so it did crash for Player/Card too? i thought i didn't changed that?
> 
> and you forgot to tag me, thats why i did this: #8331

it's likely the other types were already affected

File: forge-gui/src/main/java/forge/player/PlayerControllerHuman.java (hunk 1 above)
Comment (Hanmac) [reply forge-gui/src/main/java/forge/player/PlayerControllerHuman.java]: I don't like this `List<SpellAbility>)(Object)` cast

Imo a `IterableUtil.filter(options, SpellAbility.class)` would be cleaner
