### PR TITLE
Some fixes

### LINKED ISSUE #3797: Behavior of Ob Nixilis, Captive Kingpin in multiplayer games.
**Describe the bug**
In a multiplayer game, if I control Ob Nixilis, Captive Kingpin and I deal damage to multiple players at the same time, Ob's ability does not trigger, even though it is exactly one point of damage.

**To Reproduce**
1. Start multiplayer game
2. Cast Ob Nixilis, Captive Kingpin and any creature with power 1.
3. Attack multiple players and deals damage.

**Expected behavior**
Ob Nixilis, Captive Kingpin's ability is triggered.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version forge 1.6.58-SNAPSHOT-09.20

### LINKED ISSUE #3818: Likeness Looter incorrect ability cost
**Describe the bug**
**Likeness Looter:** *{T}: Draw a card, then discard a card.*

In a game it's currently set to:  *{1}, {T}: Draw a card, then discard a card.*

The really weird thing is that if you look at the ability of the card while in the deck editor, it's correct. It's only incorrect while actually in a game.

**Screenshots**
In deck editor:
Screenshot_20230925_063622

In a fresh game:
Screenshot_20230925_063637

### LINKED ISSUE #3819: Naf's Asp's ability doesn't work
Windows, current snapshot.

I'm in an Arabian Nights draft and Naf's Asp [ARN] has an ability that should cause them to lose life unless they pay. The effect triggers in combat and creates an effect tracked in the command zone, but the AI hasn't paid or lost any life in the following turns.

### PR DESCRIPTION
**Pull request by tool4ever**
Closes #3797
Closes #3819
Closes #3818

### CODE REVIEW

**Review by Agetian — APPROVED** [review]

File: forge-ai/src/main/java/forge/ai/ComputerUtilMana.java [hunk 1]
```diff
@@ -1689,12 +1689,16 @@ private static ListMultimap<Integer, SpellAbility> groupSourcesByManaColor(final
      * @since 1.0.15
      */
     public static int determineLeftoverMana(final SpellAbility sa, final Player player, final boolean effect) {
-        for (int i = 1; i < 100; i++) {
+        int max = 99;
+        if (sa.hasParam("XMaxLimit")) {
+            max = Math.min(max, AbilityUtils.calculateAmount(sa.getHostCard(), sa.getParam("XMaxLimit"), sa));
+        }
+        for (int i = 1; i <= max; i++) {
```
Comment (tehdiplomat) [inline forge-ai/src/main/java/forge/ai/ComputerUtilMana.java:1696]: Should we do a binary search instead of a linear search?

Comment (Hanmac) [reply forge-ai/src/main/java/forge/ai/ComputerUtilMana.java:1696]: what is your suggestion?

**Review by Agetian — APPROVED** [review]
