### PR TITLE
skip adventure spell if card is already onadventure

### LINKED ISSUE #3760: Fires of Invention lets you cast adventure from exile
**Describe the bug**
Fires of Invention lets you cast a creature spell in adventure mode repeatedly when the creature is already in exile. 

**Expected behavior**
Creatures with adventure that are already exiled because of adventure, can only be cast as creatures.

**Screenshots**
adventures-from-exile

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.6.58-SNAPSHOT-09.03

### PR DESCRIPTION
**Pull request by kevlahnota**
- closes #3760

### CODE REVIEW

File: forge-game/src/main/java/forge/game/card/Card.java [hunk 1]
```diff
@@ -6810,6 +6810,11 @@ public List<SpellAbility> getAllPossibleAbilities(final Player player, final boo
         // this can only be called by the Human
         final List<SpellAbility> abilities = Lists.newArrayList();
         for (SpellAbility sa : getSpellAbilities()) {
+            //adventure spell check
+            if (isAdventureCard() && sa.getRootAbility().isAdventure()) {
+                if (getExiledWith() != null && CardStateName.Adventure.equals(getExiledWith().getCurrentStateName()))
+                    continue; // skip since it's already on adventure
```
Comment (tool4ever) [inline forge-game/src/main/java/forge/game/card/Card.java:6816]: this is not what the rules say:
> 715.3d. Instead of putting a spell that was cast as an Adventure into its owner's graveyard as it resolves, its controller exiles it. For as long as that card remains exiled, that player may cast it. It can't be cast as an Adventure this way, **although other effects that allow a player to cast it may allow a player to cast it as an Adventure.**

does it still work with e. g. Ultimate of _Ashiok, Nightmare Muse_ on adventure card after this?
Otherwise I'm not sure it can be fixed without MayPlay refactor

Comment (Hanmac) [reply forge-game/src/main/java/forge/game/card/Card.java:6816]: chould we check if the Card was exiling itself?

Comment (Hanmac) [reply forge-game/src/main/java/forge/game/card/Card.java:6816]: > Hmn, I guess there is no generic MayPlay$ on Exile zone that could be broken by it

 Misthollow Griffin and Eternal Scourge

`You may cast CARDNAME from exile`

Comment (tool4ever) [reply forge-game/src/main/java/forge/game/card/Card.java:6816]: I meant "cast as Adventure" + another MayPlay gives permission on it

**Review by Hanmac — APPROVED** [review]
okay for now, i think

**Comment by Hanmac** [comment]
@kevlahnota @tool4ever 
It's problematic if [[Seek the Beast]] (adventure of Questing Druid) exiles another Questing Druid from the deck

It doesn't allow me to cast the second for its Adventure

**Comment by kevlahnota** [comment]
> @kevlahnota @tool4ever It's problematic if [[Seek the Beast]] (adventure of Questing Druid) exiles another Questing Druid from the deck
> 
> It doesn't allow me to cast the second for its Adventure

- fixed by #3833
