### PR TITLE
Fix transformed backside cast failing when some AltCost apply

### LINKED ISSUE #6064: NPE when combining certain alternative cost KW
Case A:
- _Hunting Velociraptor_
- _Maskwood Nexus_ (so it gets Dinosaur type)
- try cast _Beloved Beggar_ disturbed

Case B:
- Defeat battle _Invasion of Ikoria_ and try cast backside (is already Dinosaur)

```
Game-2 > java.lang.RuntimeException: Error in Keyword Prowl:2 R for card Generous Soul
	at forge.game.keyword.KeywordInstance.createTraits(KeywordInstance.java:128)
	at forge.game.keyword.KeywordInstance.createTraits(KeywordInstance.java:86)
	at forge.game.card.Card.getKeywordForStaticAbility(Card.java:5130)
	at forge.game.card.Card.addChangedCardKeywords(Card.java:5107)
	at forge.game.staticability.StaticAbilityContinuous.applyContinuousAbility(StaticAbilityContinuous.java:772)
	at forge.game.staticability.StaticAbilityContinuous.applyContinuousAbility(StaticAbilityContinuous.java:72)
	at forge.game.staticability.StaticAbility.applyContinuousAbilityBefore(StaticAbility.java:238)
	at forge.game.GameAction.checkStaticAbilities(GameAction.java:1135)
	at forge.game.GameAction.checkStaticAbilities(GameAction.java:1083)
	at forge.game.GameActionUtil.addExtraKeywordCost(GameActionUtil.java:567)
	at forge.player.HumanPlaySpellAbility.playAbility(HumanPlaySpellAbility.java:117)
	at forge.player.HumanPlay.playSpellAbility(HumanPlay.java:106)
	at forge.player.PlayerControllerHuman.playChosenSpellAbility(PlayerControllerHuman.java:1509)
	at forge.game.phase.PhaseHandler.startFirstTurn(PhaseHandler.java:1055)
	at forge.game.GameAction.startGame(GameAction.java:2131)
	at forge.game.Match.startGame(Match.java:90)
	at forge.gamemodes.match.HostedMatch.lambda$1(HostedMatch.java:269)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.lang.NullPointerException: Cannot invoke "forge.game.spellability.SpellAbility.copyWithDefinedCost(forge.game.cost.Cost)" because the return value of "forge.game.card.CardState.getFirstSpellAbility()" is null
	at forge.game.card.CardFactoryUtil.addSpellAbility(CardFactoryUtil.java:3466)
	at forge.game.keyword.KeywordInstance.createTraits(KeywordInstance.java:117)
	... 19 more
```

the problem is these alternate states don't have a `getFirstSpellAbility()` so the Prowl KW can't use it

@Hanmac
how can we handle this?
write a helper to call instead that could lazy build a SpellPermanent?

### PR DESCRIPTION
**Pull request by tool4ever**
I only patched the places that can give extrinsic alternative with defined cost.

Closes #6064

### CODE REVIEW

File: forge-game/src/main/java/forge/game/card/CardState.java [hunk 1]
```diff
@@ -377,6 +378,15 @@ public final SpellAbility getFirstSpellAbility() {
         return Iterables.getFirst(getNonManaAbilities(), null);
     }
 
+    public final SpellAbility getFirstSpellAbilityWithFallback() {
+        SpellAbility sa = getFirstSpellAbility();
+        if (sa != null) {
+            return sa;
+        }
+        // this happens if it's transformed backside (e.g. Disturbed)
+        return new SpellPermanent(getCard());
```
Comment (Hanmac) [inline forge-game/src/main/java/forge/game/card/CardState.java:387]: What happens if the backside is a Land? Then it shouldn't make SpellPermament?

Comment (tool4ever) [reply forge-game/src/main/java/forge/game/card/CardState.java:387]: Hmn, I can't think of how this would happen currently since this will only get called if it's on the Stack already

but I can add a safety check nonetheless

Comment (Hanmac) [reply forge-game/src/main/java/forge/game/card/CardState.java:387]: You probably need to add `this` as second Param for the SpellPermanent for the CardState?
Otherwise, it probably would enter as wrong CardState?

Also, you might update Disturb Keyword to use this new Function?

Comment (tool4ever) [reply forge-game/src/main/java/forge/game/card/CardState.java:387]: Fixed but I'm not sure how Disturb should use it

Comment (Hanmac) [reply forge-game/src/main/java/forge/game/card/CardState.java]: For Disturb, shouldn't this be enough?

```java
SpellAbility newSA = host.getAlternateState().getFirstSpellAbilityWithFallback().copyWithDefinedCost(disturbCost);
```

Comment (tool4ever) [reply forge-game/src/main/java/forge/game/card/CardState.java]: ah right, works fine

Comment (tool4ever) [reply forge-game/src/main/java/forge/game/card/CardState.java]: I guess it does copy the SpellPermanent now instead, but shouldn't hurt too much?

**Review by Hanmac — APPROVED** [review]
