### PR TITLE
VoteEffect: use SpellAbility Choices

### LINKED ISSUE #8236: Deadpool crash
> AbilityFactory : getAbility -- Deadpool, Trading Card has no SVar: MagisterofWorthDestroy

Looks like its because of the VoteEffect sub name scheme since others defined in `additionalAbilityKeys` work fine.

Though I wonder if that also causes more problems like with copying and text changes? 🤔

Otherwise we might need to improve the SVar fallback stuff there.

### PR DESCRIPTION
**Pull request by Hanmac**
Closes #8236 

Vote Choices use SpellAbilities now

This might help with making AI smarter

### CODE REVIEW

File: forge-game/src/main/java/forge/game/ability/effects/VoteEffect.java [hunk 1]
```diff
@@ -143,28 +141,35 @@ public void resolve(final SpellAbility sa) {
...
-                    subAbs.add(sa.getParam("Vote" + type.toString()));
+                final List<Object> mostVotes = getMostVotes(votes);
+                if (sa.hasAdditionalAbility("VoteTiedAbility") && mostVotes.size() > 1) {
+                    subAbs.add(sa.getAdditionalAbility("VoteTiedAbility"));
+                } else if (sa.hasAdditionalAbility("VoteSubAbility")) {
+                    host.addRemembered(mostVotes);
+                    subAbs.add(sa.getAdditionalAbility("VoteSubAbility"));
+                } else {
+                    for (Object type : mostVotes) {
+                        subAbs.add((SpellAbility)type);
```
Comment (tool4ever) [inline forge-game/src/main/java/forge/game/ability/effects/VoteEffect.java:160]:
```
Game-0 > java.lang.ClassCastException: class forge.game.player.Player cannot be cast to class forge.game.spellability.SpellAbility (forge.game.player.Player and forge.game.spellability.SpellAbility are in unnamed module of loader 'app')
	at forge.game.ability.effects.VoteEffect.resolve(VoteEffect.java:160)
```

Comment (Hanmac) [reply forge-game/src/main/java/forge/game/ability/effects/VoteEffect.java:160]: should be fixed

Comment (tool4ever) [reply forge-game/src/main/java/forge/game/ability/effects/VoteEffect.java:160]:
```
Game-0 > java.lang.ClassCastException: class forge.game.card.Card cannot be cast to class forge.game.spellability.SpellAbility (forge.game.card.Card and forge.game.spellability.SpellAbility are in unnamed module of loader 'app')
	at forge.game.ability.effects.VoteEffect.resolve(VoteEffect.java:160)
```

maybe the logic can be cleaned up further so you don't have to mix all these `hasParam` checks multiple times

**Review by Agetian — APPROVED** [review]
