### PR TITLE
Fix Meld cards fetch

### LINKED ISSUE #7979: Inconsistency to Scryfall Mend cards
@Eradev I reported the inconsistency to Scryfall (including some Error with the CN in SIR)

> 
> From Innistrad Remastered (INR):
> Hanweir Garrison is 157a
> Midnight Scavengers is 123 instead of 123a?
> Bruna, the Fading Light is 14a
> 
> Shadows over Innistrad Remastered (SIR)
> For this pair, I think the Melded Card has the wrong Collector Number?
> I added new Gatherer Links: 
> Graf Rats 115a should be 123? https://gatherer.wizards.com/SIR/en-us/123/graf-rats
> Chittering Host 115b is correct https://gatherer.wizards.com/SIR/en-us/115/chittering-host
> Midnight Scavengers 123 should be 115a? https://gatherer.wizards.com/SIR/en-us/115/midnight-scavengers
> 
> The Brothers' War (BRO) 
> The Mightstone and Weakstone is 238 instead of 238a?

Also, i didn't report this, but these one does mess with other "a" and "b" parts too:
> The Brothers' War Promos (PBRO) This one has "s" and "p" marks after "a" and "b"
> Phyrexian Dragon Engine 163as
> Mishra, Lost to Phyrexia 163bs

_Originally posted by @Hanmac in https://github.com/Card-Forge/forge/issues/7973#issuecomment-3051845616_

### PR DESCRIPTION
**Pull request by Eradev**
Fixes #7979 and minor fixes to other sets.

### CODE REVIEW

File: forge-core/src/main/java/forge/item/PaperCard.java [hunk 1]
```diff
@@ -154,6 +154,29 @@ public PaperCard getNoSellVersion() {
...
+        if (meldWith == null) {
+            return null;
+        }
+
+        CardDb db = StaticData.instance().getCommonCards();
+        if (db == null) {
+            return null;
+        }
+
+        return db.getCard(meldWith, this.edition, this.artIndex);
```
Comment (Hanmac) [inline forge-core/src/main/java/forge/item/PaperCard.java]: i wouldn't trust art index, that is just going to be problematic in the future

Comment (Eradev) [reply forge-core/src/main/java/forge/item/PaperCard.java]: I don't think there's another way right now to get the right reverse side without the artIndex for FIN. The set have different pictures for the each of the variations.

File: forge-gui/res/editions/Alchemy Horizons Baldur's Gate.txt [hunk 2]
```diff
@@ -276,26 +276,26 @@ ScryfallCode=HBG
 264 C Prophetic Prism @Diego Gisbert
 265 C Spiked Pit Trap @Deruchenko Alexander
 266 R Baldur's Gate @Titus Lunter
```
Comment (Hanmac) [inline forge-gui/res/editions/Alchemy Horizons Baldur's Gate.txt:278]: 267 to 289 Missing from Srcyfall

it's on Gatherer
https://gatherer.wizards.com/sets/HBG?page=4

Comment (Eradev) [reply forge-gui/res/editions/Alchemy Horizons Baldur's Gate.txt:278]: They seems to be non-existant on Scryfall, and are present as other numbers in the set. (ie. 267 is the same exact one as 82)

Comment (Hanmac) [reply forge-gui/res/editions/Alchemy Horizons Baldur's Gate.txt:278]: Scryfall says that these are duplicated entries that they not track :/

Comment (Eradev) [reply forge-gui/res/editions/Alchemy Horizons Baldur's Gate.txt:278]: It'll still work anyway for most search cases, unless they go by collector number. It's the same art and everything so nothing was lost.

Comment (Hanmac) [reply forge-gui/res/editions/Alchemy Horizons Baldur's Gate.txt:278]: i still think your MRs should be smaller about single things

@tool4ever has similar issues with doing bigger MRs

Comment (Eradev) [reply forge-gui/res/editions/Alchemy Horizons Baldur's Gate.txt:278]: I'll keep that in mind next time.

File: forge-core/src/main/java/forge/item/PaperCard.java (hunk 1 above)
Comment (kevlahnota) [reply forge-core/src/main/java/forge/item/PaperCard.java]: does meld cards for FIN have same collector number? I guess you can use getCard(final String cardName, String setCode, String collectorNumber)..

Comment (Hanmac) [reply forge-core/src/main/java/forge/item/PaperCard.java]: @kevlahnota the problem with `FIN have same collector number` isn't about finding the same collector number, but finding the other part it merges with.

if A and B are Meld into C
and the set looks like this:
```
1 A
2 B // C
3 A
4 B // C
```
How should Forge know that `3 A` melds into `4 B`?

Comment (kevlahnota) [reply forge-core/src/main/java/forge/item/PaperCard.java]: If the collector is numbered that way, isn't it obvious that it needs higher collector number with b face like in your example?

Comment (Hanmac) [reply forge-core/src/main/java/forge/item/PaperCard.java]: from FIN set:

№ 	[Name]
* [cards]
  * [99](https://scryfall.com/card/fin/99/fang-fearless-lcie) [Fang, Fearless l'Cie](https://scryfall.com/card/fin/99/fang-fearless-lcie)
  * [99b](https://scryfall.com/card/fin/99b/ragnarok-divine-deliverance) [Ragnarok, Divine Deliverance](https://scryfall.com/card/fin/99b/ragnarok-divine-deliverance)
  * [211](https://scryfall.com/card/fin/211/vanille-cheerful-lcie) [Vanille, Cheerful l'Cie](https://scryfall.com/card/fin/211/vanille-cheerful-lcie) Melds with 99
* [borderless]
  * [381](https://scryfall.com/card/fin/381/fang-fearless-lcie) [Fang, Fearless l'Cie](https://scryfall.com/card/fin/381/fang-fearless-lcie)
  * [381b](https://scryfall.com/card/fin/381b/ragnarok-divine-deliverance) [Ragnarok, Divine Deliverance](https://scryfall.com/card/fin/381b/ragnarok-divine-deliverance)
  * [392](https://scryfall.com/card/fin/392/vanille-cheerful-lcie) [Vanille, Cheerful l'Cie](https://scryfall.com/card/fin/392/vanille-cheerful-lcie) Melds with 381
* [extended art]
  * [446](https://scryfall.com/card/fin/446/fang-fearless-lcie) [Fang, Fearless l'Cie](https://scryfall.com/card/fin/446/fang-fearless-lcie)
  * [446b](https://scryfall.com/card/fin/446b/ragnarok-divine-deliverance) [Ragnarok, Divine Deliverance](https://scryfall.com/card/fin/446b/ragnarok-divine-deliverance)
  * [475](https://scryfall.com/card/fin/475/vanille-cheerful-lcie) [Vanille, Cheerful l'Cie](https://scryfall.com/card/fin/475/vanille-cheerful-lcie) Melds with 446
* [etched]
  * [526](https://scryfall.com/card/fin/526/fang-fearless-lcie) [Fang, Fearless l'Cie](https://scryfall.com/card/fin/526/fang-fearless-lcie)
  * [526b](https://scryfall.com/card/fin/526b/ragnarok-divine-deliverance) [Ragnarok, Divine Deliverance](https://scryfall.com/card/fin/526b/ragnarok-divine-deliverance)
  * [537](https://scryfall.com/card/fin/537/vanille-cheerful-lcie) [Vanille, Cheerful l'Cie](https://scryfall.com/card/fin/537/vanille-cheerful-lcie) Melds with 526

@Eradev maybe we can use the Printsheet Data for this? Assuming the MeldPair is on the Same Printsheet?
@tehdiplomat what do you think?

Comment (Eradev) [reply forge-core/src/main/java/forge/item/PaperCard.java]: Made it work with printsheets.

File: forge-gui/res/editions/New Phyrexia.txt [hunk 3]
```diff
@@ -191,6 +189,6 @@ TokenFallbackCode=MBS
 
 [tokens]
 1 g_3_3_beast @Dave Allsop
-2 r_1_1_phyrexian_goblin_haste @Jaime Jones
-3 c_3_3_a_phyrexian_golem @Volkan Baǵa
-4 c_1_1_a_phyrexian_myr @Matt Stewart
+r_1_1_phyrexian_goblin_haste
```
Comment (Hanmac) [inline forge-gui/res/editions/New Phyrexia.txt]: Why does the CN got removed?

If the token doesn't exist, the Tokenfallback code might be used

Comment (Eradev) [reply forge-gui/res/editions/New Phyrexia.txt]: Oh that's old stuff. I can probably remove them.

File: forge-core/src/main/java/forge/item/PaperCard.java (hunk 1 above)
Comment (Hanmac) [reply forge-core/src/main/java/forge/item/PaperCard.java]: @Eradev i added some helper functions for Printsheet
https://github.com/Card-Forge/forge/commit/42363204ddb44b1bd493e1fdb8ea7099a7b6c8cc

Comment (Eradev) [reply forge-core/src/main/java/forge/item/PaperCard.java]: Updated
