### PR TITLE
Fix AI can't use special mana abilities of e.g. Faeburrow Elder (#9026)

### LINKED ISSUE #9026: AI can't use special mana abilities of e.g. Faeburrow Elder
The user can, because the logic is there in `forge-game\src\main\java\forge\game\ability\effects\ManaEffect.java` `resolve`, but it's missing in `forge-game\src\main\java\forge\game\GameActionUtil.java` `generatedMana`.
As mana abilities don't use the stack, I wonder why the code even is in `resolve`.

Patch coming up.

### PR DESCRIPTION
**Pull request by CTimmerman**
Closes #9026

image

### CODE REVIEW

File: forge-game/src/main/java/forge/game/GameActionUtil.java [hunk 1]
```diff
@@ -860,6 +864,102 @@ public static String generatedMana(final SpellAbility sa) {
         } else if (sa.getApi() == ApiType.ManaReflected) {
             baseMana = abMana.getExpressChoice();
         } else if (abMana.isSpecialMana()) {
+            // Mana abilities don't use the stack so remove this part from forge-game\src\main\java\forge\game\ability\effects\ManaEffect.java ?
```
Comment (tool4ever) [inline forge-game/src/main/java/forge/game/GameActionUtil.java]: it's obviously terrible to duplicate this much code

anyway you can't abuse this function for what you want, if you check how this gets called just asking PlayerController for input will lead to unwanted side effects

Comment (CTimmerman) [reply forge-game/src/main/java/forge/game/GameActionUtil.java]: Hence the question to remove the original in resolve(); I'm not familiar enough with this 10+-year old codebase to refactor this.

What side effects? I only noticed the bug being fixed.

Comment (tool4ever) [reply forge-game/src/main/java/forge/game/GameActionUtil.java]: like Human being asked to select colors because AI does some predictions

**Comment by CTimmerman** [comment]
_Wirewood Channeler_ also works well enough:
image

File: forge-gui/res/cardsfolder/f/faeburrow_elder.txt [hunk 2]
```diff
@@ -4,7 +4,7 @@ Types:Creature Treefolk Druid
 PT:0/0
 K:Vigilance
 S:Mode$ Continuous | Affected$ Card.Self | AddPower$ X | AddToughness$ X | Description$ CARDNAME gets +1/+1 for each color among permanents you control.
+SVar:NoZeroToughnessAI:True
 SVar:X:Count$Valid Permanent.YouCtrl$Colors
 A:AB$ Mana | Cost$ T | Produced$ Special EachColorAmong_Permanent.YouCtrl | SpellDescription$ For each color among permanents you control, add one mana of that color.
-AI:RemoveDeck:All
 Oracle:Vigilance\nFaeburrow Elder gets +1/+1 for each color among permanents you control.\n{T}: For each color among permanents you control, add one mana of that color.
```
Comment (tool4ever) [inline forge-gui/res/cardsfolder/f/faeburrow_elder.txt:10]: this doesn't truly work
won't even cast a Bear Cub with it

Comment (CTimmerman) [reply forge-gui/res/cardsfolder/f/faeburrow_elder.txt:10]: Strange; here it's casting a 1R creature just fine:
image
_Bear Cub_ is 1G and the AI prefers to use land for mana.

Comment (tool4ever) [reply forge-gui/res/cardsfolder/f/faeburrow_elder.txt:10]: looks like you're showing a corner case where the AI had leftover mana from using it to pay for the Artifact 🤷‍♂️

Comment (CTimmerman) [reply forge-gui/res/cardsfolder/f/faeburrow_elder.txt:10]: Then the issue is in `forge-ai\src\main\java\forge\ai\ComputerUtilMana.java groupSourcesByManaColor`
```
"{64=[{T}: Add {C}., {T}: Add {C}., {T}: Add {G}., {T}: Add {W}., {T}: Add {G}., {T}: Add {W}., {T}: Add {G}., {T}: Add {W}., {T}: For each color among permanents you control, add one mana of that color., {T}: For each color among permanents you control, add one mana of that color.], 32=[{T}: Add {C}., {T}: Add {C}., {T}: For each color among permanents you control, add one mana of that color., {T}: For each color among permanents you control, add one mana of that color.], 16=[{T}: Add {G}., {T}: Add {G}., {T}: Add {G}.], 1=[{T}: Add {W}., {T}: Add {W}., {T}: Add {W}.]}"
```
Generic (64) contains all 10 shard sources (OK), Colorless (32) should not contain "of that color" sources (FAIL), Green (16) and White (1) both lack the "of that color" sources.

image

Comment (CTimmerman) [reply forge-gui/res/cardsfolder/f/faeburrow_elder.txt:10]: Fixed: 
image

File: forge-gui/res/cardsfolder/w/wirewood_channeler.txt [hunk 3]
```diff
@@ -4,6 +4,4 @@ Types:Creature Elf Druid
 PT:2/2
 A:AB$ Mana | Cost$ T | Produced$ Any | Amount$ X | SpellDescription$ Add X mana of any one color, where X is the number of Elves on the battlefield.
 SVar:X:Count$Valid Elf
-AI:RemoveDeck:All
-AI:RemoveDeck:Random
```
Comment (tool4ever) [inline forge-gui/res/cardsfolder/w/wirewood_channeler.txt:8]: should probably add DeckHints if you think it now belongs in random decks

Comment (CTimmerman) [reply forge-gui/res/cardsfolder/w/wirewood_channeler.txt:8]: It could be useful against elf decks, despite there being better cards for that, but i added the hint to prefer its inclusion in Elf decks.

File: forge-gui/res/cardsfolder/j/jeweled_amulet.txt [hunk 4]
```diff
@@ -4,5 +4,4 @@ Types:Artifact
 A:AB$ PutCounter | Cost$ 1 T | RememberCostMana$ True | CounterType$ CHARGE | CounterNum$ 1 | CheckSVar$ X | SVarCompare$ EQ0 | SpellDescription$ Put a charge counter on CARDNAME. Note the type of mana spent to pay this activation cost. Activate only if there are no charge counters on CARDNAME.
 SVar:X:Count$CardCounters.CHARGE
 A:AB$ Mana | Cost$ T SubCounter<1/CHARGE> | Produced$ Special LastNotedType | SpellDescription$ Add one mana of CARDNAME's last noted type.
-AI:RemoveDeck:All
```
Comment (tool4ever) [inline forge-gui/res/cardsfolder/j/jeweled_amulet.txt:7]: are you sure the AI is now playing this to store leftover mana correctly?

File: forge-game/src/main/java/forge/game/GameActionUtil.java [hunk 5]
```diff
@@ -838,6 +838,45 @@ public static String generatedTotalMana(final SpellAbility sa) {
...
+            abMana.setExpressChoice(sb.toString());
+        } else if (type.startsWith("EachColorAmong")) {
+            // Faeburrow Elder
+            final String res = type.split("_")[1];
+            final boolean defined = type.startsWith("EachColorAmongDefined");
+            final ZoneType zone = defined || type.startsWith("EachColorAmong_") ? ZoneType.Battlefield :
+                    ZoneType.smartValueOf(type.split("_")[0].substring(14));
+            final CardCollection list = defined ? AbilityUtils.getDefinedCards(card, res, sa) :
+                    CardLists.getValidCards(card.getGame().getCardsIn(zone), res, activator, card, sa);
+            byte colors = 0;
```
Comment (tool4ever) [inline forge-game/src/main/java/forge/game/GameActionUtil.java]: use ``CardUtil.getColorsFromCards``

File: forge-gui/res/cardsfolder/j/jeweled_amulet.txt (hunk 4 above)
Comment (CTimmerman) [reply forge-gui/res/cardsfolder/j/jeweled_amulet.txt:7]: Yes:
image

File: forge-game/src/main/java/forge/game/ability/effects/ManaEffect.java [hunk 6]
```diff
@@ -201,32 +198,10 @@ else if (cs.isMonoColor())
...
-                    int nMana = 0;
-                    for (Object o : card.getRemembered()) {
-                        if (o instanceof String) {
-                            sb.append(o);
-                            nMana++;
-                        }
-                    }
-                    if (nMana == 0) {
+                } else if (type.equals("LastNotedType") || type.startsWith("EachColorAmong")) {
+                    if (!GameActionUtil.setManaAbilityChoice(sa)) {
```
Comment (tool4ever) [inline forge-game/src/main/java/forge/game/ability/effects/ManaEffect.java]: I think you can probably remove this part so the code doesn't have to be executed twice while resolving

**Review by tool4ever — APPROVED** [review]
finally found some time to clean this up
