### PR TITLE
Improve AI for Workshop Elders + fix AI paying Cycling PayLife costs in presence of Living End

### LINKED ISSUE #3837: Workshop Elders unable to animate treasure token
**Describe the bug**
I was playing a commander gauntlet against the AI. The AI was playing Tinker Time precon. The AI played Workshop Elders and then tried to animate a treasure token it had created. But the ability did nothing. The token did not become a creature.

**Expected behavior**
When a treasure token is targeted by Workshop Elders' triggered ability, it should become a 0/0 creature with 4 1/1 counters on it.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.6.59-SNAPSHOT-09.29

### LINKED ISSUE #4128: AI kills itself with Street Wraith
**Describe the bug**
AI cycles Street Wraith with low health and die

**To Reproduce**
1. AI has 1-2 lifes
2. AI cycles Street Wraith

**Expected behavior**
AI shouldn't cycle Street Wraith with low health

**Desktop**
OS: Windows 10
Java Version: 1.8.0_202-b08
Forge Version: 1.6.59-SNAPSHOT-11.03

**Screenshots**

street

### PR DESCRIPTION
**Pull request by Agetian**
Fixes #3837 
Fixes #4128

### CODE REVIEW

File: forge-ai/src/main/java/forge/ai/ability/AnimateAi.java [hunk 1]
```diff
@@ -314,7 +314,8 @@ private boolean animateTgtAI(final SpellAbility sa) {
                 int aValue = ComputerUtilCard.evaluateCreature(animatedCopy);
 
                 // animated creature has zero toughness, don't do that
-                if (animatedCopy.getNetToughness() <= 0) {
+                if (animatedCopy.getNetToughness() <= 0
+                        && !(logic.equals("WithCounters") && animatedCopy.canReceiveCounters(CounterEnumType.P1P1))) {
```
[the remark this answers is not in the document]
Comment (Agetian) [reply forge-ai/src/main/java/forge/ai/ability/AnimateAi.java]: True :) Done!

File: forge-ai/src/main/java/forge/ai/AiController.java [hunk 2]
```diff
@@ -1623,8 +1626,15 @@ private SpellAbility chooseSpellAbilityToPlayFromList(final List<SpellAbility> a
             AiPlayDecision aiPlayDecision = AiPlayDecision.CantPlaySa;
             if (useLivingEnd) {
                 if (sa.isCycling() && sa.canCastTiming(player)) {
-                    if (ComputerUtilCost.canPayCost(sa, player, sa.isTrigger()))
-                        aiPlayDecision = AiPlayDecision.WillPlay;
+                    if (ComputerUtilCost.canPayCost(sa, player, sa.isTrigger())) {
```
Comment (tool4ever) [inline forge-ai/src/main/java/forge/ai/AiController.java:1629]: Honestly it makes no sense to me to create this "aggressive decision override" mode and now try to backport all kinds of sanity logic we'd normally benefit from into this single place
E.g. it's only a matter of time until we get a report where the AI cycles itself into a loss because the library was empty
Perhaps the way this mode gets enabled can be tweaked as part of the deck selection or something :/
sorry, I really don't want to sound too harsh and all...

Comment (Agetian) [reply forge-ai/src/main/java/forge/ai/AiController.java:1629]: I have no idea tbh, though I do agree with the reasoning. Not sure if I'm the best person to do the latter though, as I'm not the author of the override logic and I'm not sure if I fully understand how exactly it can be wired better to avoid this kind of situation ^^;

File: forge-ai/src/main/java/forge/ai/ability/AnimateAi.java [hunk 3]
```diff
@@ -313,10 +313,21 @@ private boolean animateTgtAI(final SpellAbility sa) {
...
                 int aValue = ComputerUtilCard.evaluateCreature(animatedCopy);
 
-                // animated creature has zero toughness, don't do that
-                if (animatedCopy.getNetToughness() <= 0
-                        && !(logic.equals("WithCounters") && animatedCopy.canReceiveCounters(CounterEnumType.P1P1))) {
-                    continue;
+                // animated creature has zero toughness, don't do that unless
+                if (animatedCopy.getNetToughness() <= 0) {
+                    boolean buffedToughness = false;
+                    SpellAbility sub = sa.getSubAbility();
```
Comment (Hanmac) [inline forge-ai/src/main/java/forge/ai/ability/AnimateAi.java:319]: you could try findSubAbilityByType

Comment (Agetian) [reply forge-ai/src/main/java/forge/ai/ability/AnimateAi.java]: True, good call! Done :)

File: forge-ai/src/main/java/forge/ai/AiController.java (hunk 2 above)
Comment (Agetian) [reply forge-ai/src/main/java/forge/ai/AiController.java:1630]: I checked the logic - as far as my possibilities go at the moment (given the available spare time), I can only either patch up the existing implementation and add a TODO for a better implementation to hopefully be coded in the future (either by me or by someone else), or I can revert my code in this branch and leave the implementation broken for both cases (life payment and library size) until someone else can patch it properly or until I can find enough time to dig deep into the question of how to rewire the logic. Please let me know what would be preferable.

Comment (tool4ever) [reply forge-ai/src/main/java/forge/ai/AiController.java:1630]: hmn, let's just leave it alone like this now? 🤔 
It's not like there will be huge negative impact, besides the approach having this general function getting a bit messier with card specific stuff ofc

Comment (Agetian) [reply forge-ai/src/main/java/forge/ai/AiController.java:1630]: Alright, sounds good, let's keep it as is for now then, and hopefully we can modify it later to have the relevant complication avoided

Comment (kevlahnota) [reply forge-ai/src/main/java/forge/ai/AiController.java:1630]: > Honestly it makes no sense to me to create this "aggressive decision override" mode and now try to backport all kinds of sanity logic we'd normally benefit from into this single place E.g. it's only a matter of time until we get a report where the AI cycles itself into a loss because the library was empty Perhaps the way this mode gets enabled can be tweaked as part of the deck selection or something :/ sorry, I really don't want to sound too harsh and all...

I don't see any different play style/variation that use Living End based deck on this stats (Living End Decks): https://mtgdecks.net/prices/living-end

So the decision is forced to pile up graveyard and use cascade to cheat/play Living End (try removing the forced decision and see what the AI will do), The logic is somehow lacking in some aspect checks but I can't introduce more logic without slowing down the AI decision.
