### PR TITLE
Fix for noted types for Volo's journal

### LINKED ISSUE #4693: AI makes illegal choices when triggering Volo's Journal
Windows, current snapshot.

The AI had `Volo, Itinerant Scholar` [CLB], and his journal. It cast `Shimmering Efreet` [VIS] which has the creature type Efreet, triggering journal, and chose Sliver. There's no effect making that a valid choice. I tested it myself and was correctly limited to choosing types that the spell actually had, so I guess it's just that the AI choice isn't made from the restricted set.

### PR DESCRIPTION
**Pull request by neoFuzz**
Aims to stop "Sliver" being the default option.

Closes #4693

### CODE REVIEW

File: forge-game/src/main/java/forge/game/ability/effects/ChooseTypeEffect.java [hunk 1]
```diff
@@ -154,4 +154,12 @@ public void resolve(SpellAbility sa) {
             throw new InvalidParameterException(sa.getHostCard() + "'s ability resulted in no types to choose from");
         }
     }
+
+    private static List<String> getInvalidTypes(SpellAbility sa) {
+        if(sa.getHostCard().hasAnyNotedType())
```
Comment (Hanmac) [inline forge-game/src/main/java/forge/game/ability/effects/ChooseTypeEffect.java:159]: this check is already done in in line 119

it is also important to check for hasParam "Note"

File: forge-ai/src/main/java/forge/ai/ComputerUtilCard.java [hunk 2]
```diff
@@ -875,12 +875,29 @@ public static String getMostProminentType(final CardCollectionView list, final C
...
-        for (final Entry<String, Integer> entry : typesInDeck.entrySet()) {
-            final String type = entry.getKey();
+        // Check if the valid list is not empty
+        if (!valid.isEmpty()) {
+            // Iterate through typesInDeck and consider only valid types
+            for (final Entry<String, Integer> entry : typesInDeck.entrySet()) {
+                final String type = entry.getKey();
+
+                // Only consider the types that are in the valid list
+                if (valid.contains(type)) {
```
Comment (tool4ever) [inline forge-ai/src/main/java/forge/ai/ComputerUtilCard.java:885]: you can save a lot of lines if you just check `valid.isEmpty() ||` here first instead

File: forge-game/src/main/java/forge/game/ability/effects/ChooseTypeEffect.java (hunk 1 above)
Comment (neoFuzz) [reply forge-game/src/main/java/forge/game/ability/effects/ChooseTypeEffect.java:159]: I was getting `empty`, which didn't sit well with me, but It was meant to be the first time selection.

Pushing an update now

File: forge-ai/src/main/java/forge/ai/ComputerUtilCard.java (hunk 2 above)
Comment (neoFuzz) [reply forge-ai/src/main/java/forge/ai/ComputerUtilCard.java:885]: I'll work it out 😅

File: forge-ai/src/main/java/forge/ai/ComputerUtil.java [hunk 3]
```diff
@@ -2572,7 +2572,13 @@ else if (logic.equals("MostProminentInComputerGraveyard")) {
                 }
             }
             if (!CardType.isACreatureType(chosen) || invalidTypes.contains(chosen)) {
-                chosen = "Sliver";
+                // assume invalid types is all non-valid types
+                List <String> invalid = Lists.newArrayList(CardType.getAllCreatureTypes());
```
[the remark this answers is not in the document]
Comment (neoFuzz) [reply forge-ai/src/main/java/forge/ai/ComputerUtil.java:2576]: I don't understand the question 100%?
tag it in the SpellAbility AILogic?

[the remark this answers is not in the document]
Comment (tool4ever) [reply forge-ai/src/main/java/forge/ai/ComputerUtil.java:2576]: well moving away from the hardcoded default is probably a good idea
but if you just move the lines after `logic != null` branch out of it you can reuse them here so only L2580 should be needed

[the remark this answers is not in the document]
Comment (neoFuzz) [reply forge-ai/src/main/java/forge/ai/ComputerUtil.java:2576]: So the whole `if` block?
I used `getMostProminentType` as a decision making tool, since you might as well note the types with the most first.

Making a script tag wouldn't be bad since only 2 cards currently use this singleton noted creature types abilitiy

[the remark this answers is not in the document]
Comment (neoFuzz) [reply forge-ai/src/main/java/forge/ai/ComputerUtil.java]: I completely reduced the code there. `invalid` wasn't used. Also added check for `validType.size() == 1` skipping get most prominent type

File: forge-game/src/main/java/forge/game/ability/effects/ChooseTypeEffect.java [hunk 4]
```diff
@@ -154,4 +154,10 @@ public void resolve(SpellAbility sa) {
             throw new InvalidParameterException(sa.getHostCard() + "'s ability resulted in no types to choose from");
         }
     }
+
+    private static List<String> getInvalidTypes(SpellAbility sa) {
+        return sa.hasParam("InvalidTypes") ?
+                Arrays.asList(sa.getParam("InvalidTypes").split(",")) :
+                new ArrayList<>();
+    }
```
Comment (kevlahnota) [inline forge-game/src/main/java/forge/game/ability/effects/ChooseTypeEffect.java:162]: Would it be better to use Collections.emptyList() if it isn't mutable?

Comment (neoFuzz) [reply forge-game/src/main/java/forge/game/ability/effects/ChooseTypeEffect.java:162]: This snippet was already like that, I just moved it to a function. If you think it's worth the change, I'll investigate

File: forge-ai/src/main/java/forge/ai/ComputerUtil.java [hunk 5]
```diff
@@ -2544,35 +2544,35 @@ public static String chooseSomeType(Player ai, String kindOfType, SpellAbility s
...
                     boolean includeTokens = !logic.endsWith("NonToken");
                     chosen = ComputerUtilCard.getMostProminentType(ai.getAllCards(), valid, includeTokens);
-                }
-                else if (logic.equals("MostProminentInComputerGraveyard")) {
+                } else if (logic.equals("MostProminentInComputerGraveyard")) {
                     chosen = ComputerUtilCard.getMostProminentType(ai.getCardsIn(ZoneType.Graveyard), valid);
                 }
             }
+
+            if (sa.getHostCard().hasAnyNotedType())
```
Comment (Hanmac) [inline forge-ai/src/main/java/forge/ai/ComputerUtil.java:2570]: add `sa.hasParam("Note")` inside the If before the other check, so it only does it when the ability uses `Note`

Comment (neoFuzz) [reply forge-ai/src/main/java/forge/ai/ComputerUtil.java:2570]: `if (sa.hasParam("Note") && sa.getHostCard().hasAnyNotedType())` or individual `if` statements?

**Comment by neoFuzz** [comment]
I have written a test to make sure it the choices are unique. Where would I add this test too?

File: forge-ai/src/main/java/forge/ai/ComputerUtil.java (hunk 5 above)
Comment (Hanmac) [reply forge-ai/src/main/java/forge/ai/ComputerUtil.java]: yeah like this

File: forge-gui-desktop/src/test/java/forge/ai/simulation/GameSimulationTest.java [hunk 6]
```diff
@@ -2548,4 +2551,70 @@ public void testBasicSpellFizzling() {
...
+        for(Card card : cards) {
+            if (card.getName().equals("Volo's Journal")) {
+                // All words are present in the iterable
+                AssertJUnit.assertTrue(areWordsInIterable(words,card.getNotedTypes()));
+            }
+        }
+
+    }
+
+    protected boolean areWordsInIterable(List<String> words, Iterable<String> iterable) {
```
Comment (Hanmac) [inline forge-gui-desktop/src/test/java/forge/ai/simulation/GameSimulationTest.java:2605]: Why not use `list.containsAll` ?

File: forge-ai/src/main/java/forge/ai/ComputerUtil.java [hunk 7]
```diff
@@ -2544,35 +2544,36 @@ public static String chooseSomeType(Player ai, String kindOfType, SpellAbility s
...
                     boolean includeTokens = !logic.endsWith("NonToken");
                     chosen = ComputerUtilCard.getMostProminentType(ai.getAllCards(), valid, includeTokens);
-                }
-                else if (logic.equals("MostProminentInComputerGraveyard")) {
+                } else if (logic.equals("MostProminentInComputerGraveyard")) {
                     chosen = ComputerUtilCard.getMostProminentType(ai.getCardsIn(ZoneType.Graveyard), valid);
                 }
             }
+
+            if (sa.hasParam("Note") && sa.getHostCard().hasAnyNotedType())
```
Comment (tool4ever) [inline forge-ai/src/main/java/forge/ai/ComputerUtil.java:2570]: this part shouldn't be needed:
the normal assumption is the api effect of the engine will already provide the legal options with its logic, so AI code can focus on logic around good choice etc.

Comment (neoFuzz) [reply forge-ai/src/main/java/forge/ai/ComputerUtil.java:2570]: I've checked it. The types are the remaining. eg: human wizard and human already noted leaves wizard left.
It'll be removed.

File: forge-gui-desktop/src/test/java/forge/ai/simulation/GameSimulationTest.java (hunk 6 above)
Comment (neoFuzz) [reply forge-gui-desktop/src/test/java/forge/ai/simulation/GameSimulationTest.java:2605]: Expanded to check for unique entries.

File: forge-ai/src/main/java/forge/ai/ComputerUtil.java (hunk 7 above)
Comment (neoFuzz) [reply forge-ai/src/main/java/forge/ai/ComputerUtil.java]: removed

**Review by tool4ever — APPROVED** [review]
seems good, thanks :)
