### PR TITLE
CreatureEvaluator tweaks + some others

### LINKED ISSUE #3903: When a spell cast by convoke, Magda is doubly triggered.
**Describe the bug**
When I cast a spell with tapping Magda by convoke, Magda, Brazen Outlaw's ability is doubly triggered.

**To Reproduce**
1. Cast a spell with convoke, tapping Magda.
2. Magda's ability is doubly triggered.(See attached image.)

**Expected behavior**
Triggering should only happen once.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser Firefox
 - Version 1.6.59-SNAPSHOT-10.13

### PR DESCRIPTION
**Pull request by tool4ever**
Closes #3903

### CODE REVIEW

**Review by Agetian — APPROVED** [review]

File: forge-ai/src/main/java/forge/ai/CreatureEvaluator.java [hunk 1]
```diff
@@ -215,6 +219,8 @@ else if (c.hasKeyword(Keyword.WITHER)) {
             } else {
                 value -= subValue(50, "doesnt-untap");
             }
+        } else {
+            value -= subValue(10 * c.getCounters(CounterEnumType.SHIELD), "stunned");
```
Comment (Hanmac) [inline forge-ai/src/main/java/forge/ai/CreatureEvaluator.java:223]: @tool4ever didn't you mean Stun counter?

Comment (tool4ever) [reply forge-ai/src/main/java/forge/ai/CreatureEvaluator.java:223]: for sure, thanks

**Comment by Hanmac** [comment]
also thanks for fixing the Curse cards, we had a issue for them, but on gitlab
