### PR TITLE
Fix Meld art download (#7858)

### LINKED ISSUE #7858: The Mightstone and Weakstone art won't load
**Describe the bug**
The Mightstone and Weakstone art won't load.

**To Reproduce**
1. Go to Deck Editor.
2. Search The Mightstone and Weakstone.
3. See art won't load.

**Expected behavior**
Load the card art.

**Screenshots**

Image

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 2.0.4 stable

**More context**

forge.log says:
Attempting to fetch: https://api.scryfall.com/cards/bro/238/en?format=image&version=normal
Failed to download card [C:\Users\C\AppData\Local\Forge\Cache\pics\cards\BRO\The Mightstone and Weakstone.full.jpg] image: Can't get input stream from URL!
Attempting to fetch: https://api.scryfall.com/cards/bro/238/?format=image&version=normal
Failed to download card [C:\Users\C\AppData\Local\Forge\Cache\pics\cards\BRO\The Mightstone and Weakstone.full.jpg] image: Can't get input stream from URL!
Attempting to fetch: https://api.scryfall.com/cards/bro/238/en?format=image&version=normal
Failed to download card [C:\Users\C\AppData\Local\Forge\Cache\pics\cards\BRO\Urza, Planeswalker.full.jpg] image: Can't get input stream from URL!
Attempting to fetch: https://api.scryfall.com/cards/bro/238/?format=image&version=normal
Failed to download card [C:\Users\C\AppData\Local\Forge\Cache\pics\cards\BRO\Urza, Planeswalker.full.jpg] image: Can't get input stream from URL!

https://api.scryfall.com/cards/bro/238/en?format=image&version=normal says:

```json
{
  "object": "error",
  "code": "not_found",
  "status": 404,
  "details": "No card found with the given ID or set code and collector number."
}
```

237 and 239 work, so it's a Scryfall problem: https://github.com/scryfall/gatherer-bugs/issues/196

Gatherer, Companion, and Cockatrice all load the card art fine though.

### PR DESCRIPTION
**Pull request by CTimmerman**
Closes #7858.

### CODE REVIEW

**Comment by tool4ever** [comment]
shouldn't this replace your older logic?

**Comment by CTimmerman** [comment]
> shouldn't this replace your older logic?

It does. Note the else and commit parent.

**Comment by tool4ever** [comment]
I look at the code and see it doesn't...
https://github.com/Card-Forge/forge/blob/2e4ca5f8f4909d298be85b6f0f4d0556ce6cbd3e/forge-core/src/main/java/forge/util/ImageUtil.java#L202-L204

File: forge-core/src/main/java/forge/util/ImageUtil.java [hunk 1]
```diff
@@ -192,6 +192,12 @@ public static String getScryfallDownloadUrl(PaperCard cp, String face, String se
         String faceParam = "";
         if (cp.getRules().getOtherPart() != null) {
             faceParam = (face.equals("back") ? "&face=back" : "&face=front");
+        } else if (cp.getRules().getSplitType() == CardSplitType.Meld
+                    && !cardCollectorNumber.endsWith("a")
+                    && !cardCollectorNumber.endsWith("b")) {
+            // Only the bottom half of a meld card shares a collector number.
+            // Hanweir Garrison EMN already has a appended.
```
Comment (Hanmac) [inline forge-core/src/main/java/forge/util/ImageUtil.java:199]: I don't know if the Collector Number should be fixed in that case

File: forge-core/src/main/java/forge/util/ImageUtil.java [hunk 2]
```diff
@@ -192,6 +192,12 @@ public static String getScryfallDownloadUrl(PaperCard cp, String face, String se
...
+            cardCollectorNumber += face.equals("back") ? "b" : "a";
         }
         if (cp.getRules().getSplitType() == CardSplitType.Meld) {
```
Comment (Hanmac) [inline forge-core/src/main/java/forge/util/ImageUtil.java]: This lines needs to be removed

**Review by Hanmac — CHANGES_REQUESTED** [review]
The old part needs to be removed

File: forge-core/src/main/java/forge/util/ImageUtil.java (hunk 2 above)
Comment (CTimmerman) [reply forge-core/src/main/java/forge/util/ImageUtil.java]: It appears the merge commit accepted both changes to the lines. Should I rebase on the Card-Forge/master and make a new PR?

**Comment by Agetian** [comment]
Looks good to me, not sure about the collector number (comment above), but this works :)

**Comment by Hanmac** [comment]
@Agetian 
> Looks good to me, not sure about the collector number (comment above), but this works :)

the Collector Number Fix is something i need to look into later with my #7846 fixes
