### PR TITLE
Fix zone choosing when searching

### LINKED ISSUE #1975: Runeforge Champion only searches library OR graveyard, not both
I cast Runeforge Champion, with all of my runes in my graveyard. I chose to search my library in order to trigger a reshuffle, but then the ability was finished resolving. I should be able to search my library and still choose to search my graveyard.

### LINKED ISSUE #1976: 702.103g If a bestowed Aura phases in unattached
> 702.103g If a bestowed Aura phases in unattached, it ceases to be bestowed. See rule 702.26, “Phasing.”

> The Question was at what point the Bestow stops being a creature, while still phased out or not? i mean it shouldn't probably matter but i think the unbestow does happen while still phased out

You're right, it seems currently there will be a short window where it still exists as Aura :/
I think I'll look into that in another PR after

_Originally posted by @tool4ever in https://github.com/Card-Forge/forge/issues/1973#issuecomment-1328342983_

### LINKED ISSUE #1977: Merfolk Sovereign can target non-Merfolk creatures
I'm in a 10th edition draft and the AI keeps using Merfolk Sovereign on non-Merfolk creatures. The way it's coded, the ability does nothing when used on a non-Merfolk, but it shouldn't be usable at all!

### LINKED ISSUE #1983: Ground Pounder (UST) triggers from library
I rolled a die and got a 6, which triggered Ground Pounder to gain trample even though it was in my library!

### PR DESCRIPTION
**Pull request by tool4ever**
Closes #1975
Closes #1983
Closes #1977
Closes #1976

### CODE REVIEW

File: forge-ai/src/main/java/forge/ai/ability/EffectAi.java [hunk 1]
```diff
@@ -216,8 +216,9 @@ public boolean apply(final Card c) {
             } else if (logic.equals("Fight")) {
                 return FightAi.canFightAi(ai, sa, 0, 0);
             } else if (logic.equals("Pump")) {
-                List<Card> options = ai.getCreaturesInPlay();
-                if (phase.isPlayerTurn(ai) && phase.getPhase().isBefore(PhaseType.COMBAT_DECLARE_BLOCKERS) && !options.isEmpty()) {
+                CardCollection options = CardLists.getValidCards(ai.getCardsIn(ZoneType.Battlefield), sa.getTargetRestrictions().getValidTgts(), ai, sa.getHostCard(), sa);
+                options = CardLists.getTargetableCards(options, sa);
```
Comment (Hanmac) [inline forge-ai/src/main/java/forge/ai/ability/EffectAi.java:220]: For this, would `getValidCardsToTarget` be better?

**Review by Agetian — APPROVED** [review]

**Review by Agetian — APPROVED** [review]
