### PR TITLE
CharmAi: support for dependent modes

### LINKED ISSUE #9044: AI targets itself with both the chosen modes of Shadrix Silverquil's ability
**Describe the bug**
Shadrix Silverquil reads: '... you may choose two. Each mode must target a different player.' But the AI chooses two and targets itself with both modes.

**To Reproduce**
1. Play a 2-player game against AI with Shardix Silverquil
2. The AI will misplay Shadrix's ability

**Expected behavior**
I expect the AI to target itself with one ability, and the other player with the other ability.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version: Unsure, sorry

### PR DESCRIPTION
**Pull request by tool4ever**
Closes #9044
Closes #10053

### CODE REVIEW

File: forge-game/src/main/java/forge/game/ability/effects/CharmEffect.java [hunk 1]
```diff
@@ -268,12 +268,17 @@ public static boolean makeChoices(SpellAbility sa) {
     }
 
     public static void chainAbilities(SpellAbility sa, List<AbilitySub> chosen) {
+        // Sort Chosen by SA order
+        chainAbilities(sa, chosen, Comparator.comparingInt(o -> o.getSVarInt("CharmOrder")));
+    }
+    public static void chainAbilities(SpellAbility sa, List<AbilitySub> chosen, Comparator<AbilitySub> comp) {
```
Comment (tool4ever) [inline forge-game/src/main/java/forge/game/ability/effects/CharmEffect.java:274]: maybe this change isn't even needed, will check later
