### PR TITLE
Solve issue 1472

### LINKED ISSUE #1472: Yurlok of Scorch Thrash and Leyline of Abundance producing too much Mana
**Describe the bug**
When Yurlok of Scorch Thrash is tapped while a Leyline of Abundance is under your control, it adds an additional 3 green mana.

**To Reproduce**
Have both Yurlok of Scorch Thrash and Leyline of Abundance under your control.
Use Yurlok's ability to add a Black, Red, Green, and an extra Green from the Leyline.
See that it added an additional 3 Green.

**Expected behavior**
A total of 4 mana should be in the pool, instead it is 7.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.6.54 Snapshot- 9/5/2022

### PR DESCRIPTION
**Pull request by Northmoc**
- closes #1472

### CODE REVIEW

File: forge-game/src/main/java/forge/game/spellability/AbilityManaPart.java [hunk 1]
```diff
@@ -168,14 +186,17 @@ public final void produceMana(final String produced, final Player player, SpellA
         // add the mana produced to the mana pool
         manaPool.add(this.lastManaProduced);
 
-        // Run triggers
-        final Map<AbilityKey, Object> runParams = AbilityKey.mapFromCard(source);
-        runParams.put(AbilityKey.Player, player);
-        runParams.put(AbilityKey.Produced, afterReplace);
-        runParams.put(AbilityKey.AbilityMana, root);
-        runParams.put(AbilityKey.Activator, root == null ? null : root.getActivatingPlayer());
+        if (runTriggers) {
```
Comment (tool4ever) [inline forge-game/src/main/java/forge/game/spellability/AbilityManaPart.java:189]: Thanks, but not good enough yet :/

The problem is if other players control _Caged Sun_ with its weird trigger, because it has Player$ condition, so skipping isn't acceptable I think

Not sure for best approach, maybe new TriggerType or whatever Hanmac suggests :P

**Comment by Hanmac** [comment]
should probably be split into two trigger:
 * Caged Sun should Trigger When Player P adds mana to their mana pool, where it doesn't matter who is the reason to add it (and should probably differ per player)
 * Leyline (and probably all others) cares about who is activating the mana ability

**Comment by Hanmac** [comment]
The Taps for Mana should probably be outside the loop if possible, but for this I need to check existing cards

File: forge-gui/res/cardsfolder/c/caged_sun.txt [hunk 2]
```diff
@@ -4,6 +4,6 @@ Types:Artifact
 K:ETBReplacement:Other:ChooseColor
 SVar:ChooseColor:DB$ ChooseColor | Defined$ You | AILogic$ MostProminentInComputerDeck | SpellDescription$ As CARDNAME enters the battlefield, choose a color.
 S:Mode$ Continuous | Affected$ Creature.ChosenColor+YouCtrl | AddPower$ 1 | AddToughness$ 1 | Description$ Creatures you control of the chosen color get +1/+1.
-T:Mode$ TapsForMana | ValidCard$ Land | Produced$ ChosenColor | NoTapCheck$ True | Player$ You | Execute$ TrigMana | TriggerZones$ Battlefield | Static$ True | TriggerDescription$ Whenever a land's ability causes you to add one or more mana of the chosen color, add one additional mana of that color.
-SVar:TrigMana:DB$ Mana | Produced$ Chosen | Amount$ 1 | Defined$ You
+T:Mode$ ManaAdded | ValidSource$ Land | Produced$ ChosenColor | Player$ You | Execute$ TrigMana | TriggerZones$ Battlefield | Static$ True | TriggerDescription$ Whenever a land's ability causes you to add one or more mana of the chosen color, add one additional mana of that color.
```
Comment (tool4ever) [inline forge-gui/res/cardsfolder/c/caged_sun.txt:7]: New ruling:
>An ability that triggers from the resolution of an activated mana ability is also a mana ability. This means that if the land's ability that caused you to add mana was an activated mana ability, Caged Sun's triggered ability won't use the stack and can't be responded to. 

So it can be either Static or not...

I think we could just add a second trigger and then do `ValidSA$ SpellAbility.nonManaAbility`?

**Review by tool4ever — CHANGES_REQUESTED** [review]
Needs small patch here:
https://github.com/Card-Forge/forge/blob/4392fa7d4d8f61c11b8d1f136e56b81dc343eb98/forge-game/src/main/java/forge/game/spellability/SpellAbility.java#L374

File: forge-game/src/main/java/forge/game/ability/effects/ManaEffect.java [hunk 3]
```diff
@@ -240,7 +241,8 @@ else if (cs.isMonoColor())
                 continue;
             }
 
-            abMana.produceMana(mana, p, sa);
+            abMana.produceMana(mana, p, sa, runTriggers);
+            runTriggers = false; //avoid running TapsForMana triggers for each player
```
Comment (Hanmac) [inline forge-game/src/main/java/forge/game/ability/effects/ManaEffect.java:245]: The Taps for Mana Trigger should be outside of this loop

Comment (tool4ever) [reply forge-game/src/main/java/forge/game/ability/effects/ManaEffect.java:245]: The trigger is dependent on `ProduceMana` RE though

if we keep that inside `produceMana` needs to return replaced mana Strings that are all combined?

Comment (Hanmac) [reply forge-game/src/main/java/forge/game/ability/effects/ManaEffect.java:245]: i would need to checkout the trigger and existing, but TapsForMana probably need to get the ProducedMana as Player => String Map?

we need to check if the TapsForMana trigger care about who is tapping for mana (probably you) and for who the mana is produced. (i don't think that current trigger does care for this)

Comment (tool4ever) [reply forge-game/src/main/java/forge/game/ability/effects/ManaEffect.java:245]: Yea I see no trigger where it matters

File: forge-gui/res/cardsfolder/f/false_dawn.txt [hunk 4]
```diff
@@ -3,7 +3,7 @@ ManaCost:1 W
 Types:Sorcery
 A:SP$ Effect | Cost$ 1 W | ReplacementEffects$ FDRep | StaticAbilities$ FDManaConvertion | SubAbility$ DBDraw | SpellDescription$ Until end of turn, spells and abilities you control that would add colored mana instead add that much white mana. Until end of turn, you may spend white mana as though it were mana of any color. Draw a card.
 SVar:DBDraw:DB$ Draw | NumCards$ 1
-SVar:FDRep:Event$ ProduceMana | ActiveZones$ Command | ValidAbility$ SpellAbility.YouCtrl | ReplaceWith$ ProduceW | Description$ Spells and abilities you control that would add colored mana add that much white mana instead.
+SVar:FDRep:Event$ ProduceMana | ActiveZones$ Command | ValidAbility$ SpellAbility.YouCtrl | NonManaAbility$ True | ReplaceWith$ ProduceW | Description$ Spells and abilities you control that would add colored mana add that much white mana instead.
```
Comment (Hanmac) [inline forge-gui/res/cardsfolder/f/false_dawn.txt:6]: Why does this exclude mana abilities?

File: forge-game/src/main/java/forge/game/ability/effects/ManaReflectedEffect.java [hunk 5]
```diff
@@ -21,18 +21,20 @@ public class ManaReflectedEffect extends SpellAbilityEffect {
...
-        AbilityManaPart ma = sa.getManaPart();
         sa.setUndoable(sa.isAbility() && sa.isUndoable() && sa.getSubAbility() == null);
 
-        final Collection<String> colors = CardUtil.getReflectableManaColors(sa);
-
+        final StringBuilder producedMana = new StringBuilder();
         for (final Player player : getTargetPlayers(sa)) {
             final String generated = generatedReflectedMana(sa, colors, player);
-            ma.produceMana(generated, player, sa);
+            producedMana.append(ma.produceMana(generated, player, sa));
```
Comment (Hanmac) [inline forge-game/src/main/java/forge/game/ability/effects/ManaReflectedEffect.java:33]: You probably need a space after this?

File: forge-game/src/main/java/forge/game/ability/effects/ManaEffect.java [hunk 6]
```diff
@@ -241,9 +243,11 @@ else if (cs.isMonoColor())
                 continue;
             }
 
-            abMana.produceMana(mana, p, sa);
+            producedMana.append(abMana.produceMana(mana, p, sa));
         }
 
+        abMana.tapsForMana(sa, producedMana.toString());
```
Comment (Hanmac) [inline forge-game/src/main/java/forge/game/ability/effects/ManaEffect.java:249]: You probably need a space after this?

File: forge-gui/res/cardsfolder/f/false_dawn.txt (hunk 4 above)
Comment (tool4ever) [reply forge-gui/res/cardsfolder/f/false_dawn.txt:6]: No, this is the only card that should include them, all others don't work for Spells etc.:
> 106.12b. A replacement effect that applies if a permanent "is tapped for mana" or tapped for mana of a specific type and/or amount modifies the mana production event while such an ability is resolving and producing mana or the specified type and/or amount of mana.

Comment (Hanmac) [reply forge-gui/res/cardsfolder/f/false_dawn.txt:6]: But wouldn't your change stop this from working with mana abilities?

I'm pretty sure the card should work on mana abilities

Comment (tool4ever) [reply forge-gui/res/cardsfolder/f/false_dawn.txt:6]: Works as expected, the param enables it for nonmana.

Example:
_Deathrite Shaman + Ashaya_ = _Naked Singularity_ in play only replaces the granted from Forest, the Deathrite can still produce any with his own
If _False Dawn_ resolved instead both would only produce {W}

Comment (Hanmac) [reply forge-gui/res/cardsfolder/f/false_dawn.txt:6]: But it should be work on mana abilities too

There is nothing telling on False Dawn doesn't work on mana abilities

Comment (tool4ever) [reply forge-gui/res/cardsfolder/f/false_dawn.txt:6]: Yea I agree and that works
with False Dawn all lands etc. tap for {W}

Comment (tool4ever) [reply forge-gui/res/cardsfolder/f/false_dawn.txt:6]: Should be ok to merge?

Comment (Hanmac) [reply forge-gui/res/cardsfolder/f/false_dawn.txt:6]: imo NonManaAbility should be removed

Comment (tool4ever) [reply forge-gui/res/cardsfolder/f/false_dawn.txt:6]: - If I remove it _False Dawn_ can no longer replace mana from spells, that's wrong
- If I remove the `isManaAbility()` check in `ReplaceProduceMana` completely cards like _Naked Singularity_ would also replace nonmana like of _Deathrite Shaman_, that's also wrong
- the other solution would be to update such other cards with `ValidAbility$ Activated.hasTapCost**+ManaAbility**` instead - is that what you'd prefer?

Comment (Hanmac) [reply forge-gui/res/cardsfolder/f/false_dawn.txt:6]: but currently, `NonManaAbility$ True` would stop it working with ManaAbilities, and thats also wrong?

Comment (tool4ever) [reply forge-gui/res/cardsfolder/f/false_dawn.txt:6]: nooo, I'm telling you it means Include "non" not exclude:
image

Comment (Hanmac) [reply forge-gui/res/cardsfolder/f/false_dawn.txt:6]: we probably need to update later what `NonManaAbility` means at this point

we can merge this for now, but i think that might need some cleanup later.

IMO `Activated.hasTapCost+ManaAbility` would be good too

**Review by tool4ever — APPROVED** [review]
