### PR TITLE
Some cleaning brought with smaller fixes

### LINKED ISSUE #6025: Rootcast Apprenticeship: 3 instead of 2 counters
**Describe the bug**
When casting Rootcast Apprenticeship, it allows to put three +1/+1 counters on target creature, up to three times. 

**To Reproduce**
1. Cast Rootcast Apprenriceship
2. Select "Put three +1/+1 counters on target creature."

**Expected behavior**
Putting two +1/+1 counters on target creatures, as the card reads. 

**Desktop (please complete the following information):**
 - OS: Fedora 40
 - Version 1.6.64

### PR DESCRIPTION
**Pull request by tool4ever**
Fixed Phasing triggers to fully wait with their checks until the whole process is done:
> If King of the Oathbreakers phases in at the same time as one or more other Spirits you control, King of the Oathbreakers's last ability will trigger for each of them. 

Closes #6025

### CODE REVIEW

File: forge-game/src/main/java/forge/game/card/CardLists.java [hunk 1]
```diff
@@ -414,7 +414,7 @@ public static CardCollection getCardsWithLowestCMC(Iterable<Card> cardList) {
     public static int getTotalPower(Iterable<Card> cardList, boolean ignoreNegativePower, boolean crew) {
         int total = 0;
         for (final Card crd : cardList) {
-            if (crew && StaticAbilityCrewValue.hasAnyCrewValue(crd)) {
+            if (crew) {
```
Comment (Hanmac) [inline forge-game/src/main/java/forge/game/card/CardLists.java:417]: isn't that for "can't crew" effects?

Comment (tool4ever) [reply forge-game/src/main/java/forge/game/card/CardLists.java:417]: CantCrew is another static
this check was just slowing things down
if there's a relevant static there they all need to be checked below anyway for which modifier should apply

**Review by Hanmac — APPROVED** [review]
next time, do smaller MR!
